// SPDX-License-Identifier: Apache-2.0
// TCRN-CROSS-STORY-380: the generated-artifact blob store.
//
// `workspace.generatedArtifactsPath` existed from TCRN-CROSS-STORY-213 onward with no
// consumer at all: nothing in the engine ever read it, so the one setting that says
// where generated bytes belong could not move a single byte. This module is the
// consumer, and it is deliberately the SAME shape the engine already uses for stored
// bytes rather than a second storage path — SegmentedBackend's manifest (segmented-
// backend.ts) records `name`/`bytes`/`sha256` per segment beside a schema-versioned
// document, and workspace-snapshot.ts proves a copied tree by recomputing sha256 over
// what is on disk. A blob store is those two ideas with the name derived from the
// content instead of a counter.
//
// Three properties are load-bearing, and each is here because of something the
// retired artifact-lifecycle.ts got wrong (TCRN-CROSS-STORY-358 removed it):
//
//   * The blob is named for the sha256 of its PLAINTEXT while the file holds the
//     deflate stream of that plaintext. The old module base64-encoded the bytes and
//     compressed nothing, which is a 33% expansion sold as an archive; deflate is the
//     same codec workspace.ts already uses for replay snapshots, so the archive format
//     is one decision in this repository rather than two. The name stays the plaintext
//     digest because that is what "content-addressed" means to a caller: the same file
//     put twice is the same blob, whatever the compressor did with it.
//   * Every write is read back from disk and re-hashed before the receipt is emitted.
//     This is what makes a cloud-synced directory usable rather than forbidden: a sync
//     client that rewrites bytes is caught at the moment it happens, by the writer,
//     instead of being discovered years later by a reader (see docs/adr/0002).
//   * There is no FIXTURE- gate. The old module refused to archive anything unless the
//     workspace's externalKey began with `FIXTURE-`, which made the capability real
//     only for test fixtures — a verb that cannot be used by the person who needs it
//     is not a capability. Admission here is the path conditions below and nothing
//     else.
//
// The chain and the lease never leave the workspace. Only immutable blobs are written
// to the configured root, and the manifest that indexes them stays in the workspace
// control tree, so an operator can point the root at a managed directory without any
// governed state following it there.

import { createHash } from "node:crypto";
import { lstat, mkdir, open, readdir, realpath, rename, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, isAbsolute, relative, resolve, sep } from "node:path";
import { deflateSync, inflateSync } from "node:zlib";

import { assertCanonicalJson, assertStrictInstant, canonicalJson, compareCanonicalText } from "../../protocol/src/index.js";
import type { JsonValue } from "../../protocol/src/index.js";
import { MACHINE_SETTINGS_DIRECTORY } from "./machine-settings.js";
import { SETTINGS_CATALOG } from "./settings.js";
import { WORKSPACE_CONTROL_DIRECTORY } from "./storage-backend.js";
import { materializeWorkspace } from "./workspace.js";
import type { WorkspaceLease } from "./workspace.js";

export const ARTIFACT_MANIFEST_SCHEMA_VERSION = "tcrn.artifact-manifest.v1" as const;
export const ARTIFACT_PUT_SCHEMA_VERSION = "tcrn.artifact-put.v1" as const;
export const ARTIFACT_LIST_SCHEMA_VERSION = "tcrn.artifact-list.v1" as const;
export const ARTIFACT_VERIFY_SCHEMA_VERSION = "tcrn.artifact-verify.v1" as const;

/** The manifest file, always inside the workspace control tree — never beside the blobs. */
export const ARTIFACT_MANIFEST_FILE_NAME = "artifact-manifest.json" as const;

/** The setting that names the blob root. There is exactly one, and this is it. */
export const ARTIFACT_ROOT_SETTING_KEY = "workspace.generatedArtifactsPath" as const;

// The same ceiling SegmentedBackend.readSegment uses for one stored file. A blob store
// with no bound is a memory exhaustion waiting for a large input, and a bound invented
// per module is a second answer to a question this repository already answered.
export const ARTIFACT_BYTES_MAX = 67_108_864;

// New frozen reason-code list owned by this module, sorted. WORKSPACE_REASON_CODES is
// not edited, exactly as workspace-snapshot.ts declares its own.
export const ARTIFACT_REASON_CODES = Object.freeze([
  "ARTIFACT_INPUT_INVALID",
  "ARTIFACT_LIST_READY",
  "ARTIFACT_MANIFEST_INVALID",
  "ARTIFACT_MISMATCH",
  "ARTIFACT_PATH_INVALID",
  "ARTIFACT_PUT_COMMITTED",
  "ARTIFACT_VERIFIED",
] as const);

export type ArtifactReasonCode = typeof ARTIFACT_REASON_CODES[number];

export class ArtifactError extends Error {
  readonly reasonCode: ArtifactReasonCode;

  constructor(reasonCode: ArtifactReasonCode, message: string) {
    super(message);
    this.name = "ArtifactError";
    this.reasonCode = reasonCode;
  }
}

export interface ArtifactManifestEntry {
  /** sha256 of the PLAINTEXT, lowercase hex. Also the stored file's stem. */
  readonly sha256: string;
  /** Plaintext byte length. */
  readonly bytes: number;
  /** Byte length of the deflate stream actually on disk. */
  readonly storedBytes: number;
  /** The source file's base name, kept so a human can find a blob without its digest. */
  readonly name: string;
  readonly storedAt: string;
}

export interface ArtifactManifestDocument {
  readonly schemaVersion: typeof ARTIFACT_MANIFEST_SCHEMA_VERSION;
  readonly artifacts: readonly ArtifactManifestEntry[];
}

export interface ArtifactVerifyFinding {
  readonly sha256: string;
  readonly finding: "missing" | "unreadable" | "digest-mismatch" | "size-mismatch";
  readonly detail: string;
}

function fail(reasonCode: ArtifactReasonCode, message: string): never {
  throw new ArtifactError(reasonCode, message);
}

function isJsonObject(value: JsonValue | undefined): value is { readonly [key: string]: JsonValue } {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function isInside(parent: string, candidate: string): boolean {
  const relation = relative(parent, candidate);
  return relation === "" || (!relation.startsWith("..") && !relation.startsWith(sep));
}

function sha256(bytes: Buffer): string {
  return createHash("sha256").update(bytes).digest("hex");
}

const DIGEST_PATTERN = /^[0-9a-f]{64}$/u;
const BLOB_SUFFIX = ".bin";

// Bound a directory the same way workspace-snapshot.ts's boundReadDirectory does: lstat
// before, realpath, lstat after, and compare identity. A single stat cannot tell a
// directory from a symlink that became one between the two reads, and a sync client is
// precisely the thing that changes an inode under a reader.
async function boundDirectory(path: string): Promise<string> {
  let before;
  try {
    before = await lstat(path);
  } catch (error) {
    fail("ARTIFACT_PATH_INVALID", `${path}: ${String((error as { code?: string }).code ?? error)}`);
  }
  if (before.isSymbolicLink() || !before.isDirectory()) {
    fail("ARTIFACT_PATH_INVALID", `${path} must be a real directory, not a symbolic link`);
  }
  const resolved = await realpath(path);
  const after = await lstat(resolved);
  if (!after.isDirectory() || before.dev !== after.dev || before.ino !== after.ino) {
    fail("ARTIFACT_PATH_INVALID", `${path} changed while resolving`);
  }
  return resolved;
}

async function boundFileBytes(path: string, maximumBytes: number): Promise<Buffer> {
  let handle;
  try {
    handle = await open(path, "r");
  } catch (error) {
    fail("ARTIFACT_PATH_INVALID", `${path}: ${String((error as { code?: string }).code ?? error)}`);
  }
  try {
    const stats = await handle.stat();
    if (!stats.isFile()) fail("ARTIFACT_PATH_INVALID", `${path} must be a regular file`);
    if (stats.size > maximumBytes) {
      fail("ARTIFACT_INPUT_INVALID", `${path} is ${String(stats.size)} bytes, over the ${String(maximumBytes)} byte ceiling`);
    }
    return await handle.readFile();
  } finally {
    await handle.close();
  }
}

/**
 * The effective blob root for a workspace, resolved but NOT yet proved to exist.
 *
 * A relative value is workspace-relative, which is what the setting has always meant
 * and what its default (`.tcrn-workflow/artifacts`) still is. An absolute value is
 * taken as written.
 */
export function resolveGeneratedArtifactsRoot(workspaceRoot: string, value: string): string {
  return isAbsolute(value) ? resolve(value) : resolve(workspaceRoot, value);
}

/**
 * The half of the setting's admission rule that only a live filesystem can answer.
 *
 * The division of labour is deliberate and is not repeated on both sides. settings.ts
 * decides SHAPE and CONTAINMENT — normalized, no backslash, outside the workspace and its
 * control tree — because validateWorkspaceSettingRecord runs on the REPLAY path, so those
 * predicates are re-answered every time the chain is read, on every machine. This function
 * decides the two things a replay must never ask: whether the directory is inside THIS
 * machine's control home, and whether it is a real directory rather than a symbolic link
 * or a file. Asking either of those on the replay path would make a chain recorded on one
 * machine unreplayable on the next, which is the opposite of what a portable
 * content-addressed store is for.
 *
 * Containment is therefore NOT re-checked here. It is not trust: putArtifact reaches this
 * value through materializeWorkspace, whose settings reducer runs validateWorkspaceSettingRecord
 * over the record again, so the containment rule has already been enforced against this
 * exact value on this exact read.
 *
 * A relative value is left to the engine: it names a directory inside the workspace the
 * engine owns and may create. Only an absolute value can name something the engine does
 * not own, so only an absolute value is asserted against.
 */
export async function assertGeneratedArtifactsRoot(
  workspaceRoot: string,
  value: string,
  home: string = homedir(),
): Promise<string> {
  if (typeof workspaceRoot !== "string" || workspaceRoot.length === 0) {
    fail("ARTIFACT_INPUT_INVALID", "workspace root");
  }
  if (typeof value !== "string" || value.length === 0) {
    fail("ARTIFACT_INPUT_INVALID", ARTIFACT_ROOT_SETTING_KEY);
  }
  const workspace = resolve(workspaceRoot);
  const root = resolveGeneratedArtifactsRoot(workspace, value);
  if (!isAbsolute(value)) {
    await mkdir(root, { recursive: true });
    return boundDirectory(root);
  }
  if (isInside(resolve(home, MACHINE_SETTINGS_DIRECTORY), root)) {
    fail("ARTIFACT_PATH_INVALID", `${ARTIFACT_ROOT_SETTING_KEY} must be outside the machine control home`);
  }
  return boundDirectory(root);
}

async function effectiveArtifactsSetting(workspaceRoot: string): Promise<string> {
  const state = await materializeWorkspace(workspaceRoot);
  const record = state.settings.find((entry) => entry.key === ARTIFACT_ROOT_SETTING_KEY);
  if (record !== undefined) return record.value;
  const catalogDefault = SETTINGS_CATALOG.find((entry) => entry.key === ARTIFACT_ROOT_SETTING_KEY)?.defaultValue;
  if (typeof catalogDefault !== "string" || catalogDefault.length === 0) {
    fail("ARTIFACT_INPUT_INVALID", `${ARTIFACT_ROOT_SETTING_KEY} has no effective value`);
  }
  return catalogDefault;
}

function manifestPath(workspaceRoot: string): string {
  return resolve(workspaceRoot, WORKSPACE_CONTROL_DIRECTORY, ARTIFACT_MANIFEST_FILE_NAME);
}

function validateManifest(value: JsonValue): ArtifactManifestDocument {
  if (!isJsonObject(value) || value.schemaVersion !== ARTIFACT_MANIFEST_SCHEMA_VERSION || !Array.isArray(value.artifacts)) {
    fail("ARTIFACT_MANIFEST_INVALID", "artifact manifest");
  }
  const artifacts: ArtifactManifestEntry[] = [];
  const seen = new Set<string>();
  for (const raw of value.artifacts) {
    if (!isJsonObject(raw)) fail("ARTIFACT_MANIFEST_INVALID", "artifact entry");
    const { sha256: digest, bytes, storedBytes, name, storedAt } = raw;
    if (typeof digest !== "string" || !DIGEST_PATTERN.test(digest) || seen.has(digest)) {
      fail("ARTIFACT_MANIFEST_INVALID", "artifact entry digest");
    }
    if (typeof bytes !== "number" || !Number.isSafeInteger(bytes) || bytes < 0 ||
      typeof storedBytes !== "number" || !Number.isSafeInteger(storedBytes) || storedBytes < 0) {
      fail("ARTIFACT_MANIFEST_INVALID", `artifact entry ${digest} sizes`);
    }
    if (typeof name !== "string" || name.length === 0 || typeof storedAt !== "string") {
      fail("ARTIFACT_MANIFEST_INVALID", `artifact entry ${digest} fields`);
    }
    try { assertStrictInstant(storedAt); } catch { fail("ARTIFACT_MANIFEST_INVALID", `artifact entry ${digest} storedAt`); }
    seen.add(digest);
    artifacts.push({ sha256: digest, bytes, storedBytes, name, storedAt });
  }
  return { schemaVersion: ARTIFACT_MANIFEST_SCHEMA_VERSION, artifacts };
}

async function readManifest(workspaceRoot: string): Promise<ArtifactManifestDocument> {
  const path = manifestPath(workspaceRoot);
  let stats;
  try {
    stats = await lstat(path);
  } catch {
    return { schemaVersion: ARTIFACT_MANIFEST_SCHEMA_VERSION, artifacts: [] };
  }
  if (!stats.isFile() || stats.isSymbolicLink() || stats.nlink !== 1) {
    fail("ARTIFACT_MANIFEST_INVALID", `${ARTIFACT_MANIFEST_FILE_NAME} is not a plain regular file`);
  }
  const bytes = await boundFileBytes(path, ARTIFACT_BYTES_MAX);
  let parsed: JsonValue;
  try {
    parsed = assertCanonicalJson(bytes.toString("utf8"));
  } catch (error) {
    fail("ARTIFACT_MANIFEST_INVALID", String(error));
  }
  return validateManifest(parsed);
}

// Atomic in the same directory, then read back: a rename inside one directory is the
// only write this store makes durable, and the read-back is what a synced directory is
// admitted on. Staging beside the target rather than in a temp directory keeps the
// rename on one filesystem, which is the only way it stays atomic.
async function writeAtomic(path: string, content: Buffer): Promise<void> {
  const staging = `${path}.tmp-${String(process.pid)}`;
  // Clear the staging name first. A run killed between write and rename leaves one behind,
  // and pids are reused; an exclusive create would turn that stale file into a permanent
  // refusal of the one blob it belonged to. The staging name is this process's to own.
  await rm(staging, { force: true });
  await writeFile(staging, content);
  try {
    await rename(staging, path);
  } catch (error) {
    await rm(staging, { force: true });
    fail("ARTIFACT_PATH_INVALID", `${path}: ${String((error as { code?: string }).code ?? error)}`);
  }
}

async function writeManifest(workspaceRoot: string, document: ArtifactManifestDocument): Promise<void> {
  const serialised = canonicalJson({
    schemaVersion: document.schemaVersion,
    artifacts: document.artifacts.map((entry) => ({
      bytes: entry.bytes,
      name: entry.name,
      sha256: entry.sha256,
      storedAt: entry.storedAt,
      storedBytes: entry.storedBytes,
    })),
  });
  if (Buffer.byteLength(serialised, "utf8") > ARTIFACT_BYTES_MAX) {
    fail("ARTIFACT_MANIFEST_INVALID", `${ARTIFACT_MANIFEST_FILE_NAME} would exceed the ${String(ARTIFACT_BYTES_MAX)} byte ceiling`);
  }
  const path = manifestPath(workspaceRoot);
  const staging = `${path}.tmp-${String(process.pid)}`;
  await rm(staging, { force: true });
  await writeFile(staging, serialised, "utf8");
  await rename(staging, path);
}

// The lease proof, in the same shape workspace-snapshot.ts asserts it: the token in hand
// must be the token the control tree records as the holder.
async function assertHeldLease(workspaceRoot: string, lease: WorkspaceLease): Promise<void> {
  if (lease === null || typeof lease !== "object" || typeof lease.token !== "string" || lease.workspaceRoot !== workspaceRoot) {
    fail("ARTIFACT_INPUT_INVALID", "lease does not hold this workspace");
  }
  const ownerPath = resolve(workspaceRoot, WORKSPACE_CONTROL_DIRECTORY, "lease", "owner.json");
  const content = await boundFileBytes(ownerPath, 16_384);
  let owner: JsonValue;
  try {
    owner = assertCanonicalJson(content.toString("utf8"));
  } catch (error) {
    fail("ARTIFACT_INPUT_INVALID", String(error));
  }
  if (!isJsonObject(owner) || owner.schemaVersion !== "tcrn.workspace-lease.v1" || owner.token !== lease.token) {
    fail("ARTIFACT_INPUT_INVALID", "lease token does not match the recorded holder");
  }
}

function blobPath(root: string, digest: string): string {
  return resolve(root, `${digest}${BLOB_SUFFIX}`);
}

// The single reader every path uses, so "what is in this blob" has one answer. A flipped
// byte usually breaks the deflate stream outright and occasionally survives it with
// different plaintext; both are the same finding to a caller, so both come back as one.
function inflateStoredBlob(stored: Buffer): { readonly plaintext: Buffer } | { readonly error: string } {
  try {
    return { plaintext: inflateSync(stored) };
  } catch (error) {
    return { error: String((error as { message?: string }).message ?? error) };
  }
}

export interface ArtifactPutReceipt {
  readonly schemaVersion: typeof ARTIFACT_PUT_SCHEMA_VERSION;
  readonly reasonCode: "ARTIFACT_PUT_COMMITTED";
  readonly sha256: string;
  readonly bytes: number;
  readonly storedBytes: number;
  readonly name: string;
  readonly storedAt: string;
  readonly blobName: string;
  readonly deduplicated: boolean;
  readonly artifacts: number;
}

/**
 * Put one file into the workspace's configured blob root, named for its content.
 *
 * The lease is the quiesce proof, exactly as it is for `snapshot-manifest`: two callers
 * appending to one manifest without it would each write a manifest missing the other's
 * entry, and the loser's blob would be on disk with nothing pointing at it.
 */
export async function putArtifact(
  workspaceRootInput: string,
  lease: WorkspaceLease,
  options: { readonly file: string; readonly at: string },
): Promise<ArtifactPutReceipt> {
  if (typeof workspaceRootInput !== "string" || workspaceRootInput.length === 0) {
    fail("ARTIFACT_INPUT_INVALID", "workspace root");
  }
  if (options === null || typeof options !== "object" || typeof options.file !== "string" || options.file.length === 0) {
    fail("ARTIFACT_INPUT_INVALID", "file");
  }
  try { assertStrictInstant(options.at); } catch { fail("ARTIFACT_INPUT_INVALID", "at"); }
  const workspace = await boundDirectory(workspaceRootInput);
  await assertHeldLease(workspace, lease);
  const root = await assertGeneratedArtifactsRoot(workspace, await effectiveArtifactsSetting(workspace));

  const source = resolve(options.file);
  const plaintext = await boundFileBytes(source, ARTIFACT_BYTES_MAX);
  const digest = sha256(plaintext);
  const name = basename(source);
  const target = blobPath(root, digest);

  let stored: Buffer;
  let deduplicated = false;
  const existing = await lstat(target).catch(() => null);
  if (existing !== null) {
    // Content addressing makes a repeat put a no-op — but only once the bytes already
    // there are proved to be the bytes this digest names. Trusting the file name is the
    // whole failure this store exists to catch.
    if (!existing.isFile() || existing.isSymbolicLink()) {
      fail("ARTIFACT_PATH_INVALID", `${target} exists and is not a regular file`);
    }
    stored = await boundFileBytes(target, ARTIFACT_BYTES_MAX);
    const readBack = inflateStoredBlob(stored);
    if ("error" in readBack || sha256(readBack.plaintext) !== digest) {
      fail("ARTIFACT_MISMATCH", `${digest}${BLOB_SUFFIX} already present and does not match its digest`);
    }
    deduplicated = true;
  } else {
    stored = deflateSync(plaintext);
    await writeAtomic(target, stored);
    // The read-back. Written and read as two separate operations against the real path,
    // because the thing being tested is the storage layer between them.
    const verified = await boundFileBytes(target, ARTIFACT_BYTES_MAX);
    const readBack = inflateStoredBlob(verified);
    if ("error" in readBack || sha256(readBack.plaintext) !== digest) {
      await rm(target, { force: true });
      fail("ARTIFACT_MISMATCH", `${digest}${BLOB_SUFFIX} did not read back as written`);
    }
    stored = verified;
  }

  const manifest = await readManifest(workspace);
  const entry: ArtifactManifestEntry = {
    sha256: digest,
    bytes: plaintext.length,
    storedBytes: stored.length,
    name,
    storedAt: options.at,
  };
  const artifacts = [...manifest.artifacts.filter((candidate) => candidate.sha256 !== digest), entry]
    .sort((left, right) => compareCanonicalText(left.sha256, right.sha256));
  await writeManifest(workspace, { schemaVersion: ARTIFACT_MANIFEST_SCHEMA_VERSION, artifacts });

  return {
    schemaVersion: ARTIFACT_PUT_SCHEMA_VERSION,
    reasonCode: "ARTIFACT_PUT_COMMITTED",
    sha256: digest,
    bytes: entry.bytes,
    storedBytes: entry.storedBytes,
    name: entry.name,
    storedAt: entry.storedAt,
    blobName: `${digest}${BLOB_SUFFIX}`,
    deduplicated,
    artifacts: artifacts.length,
  };
}

export interface ArtifactListing {
  readonly schemaVersion: typeof ARTIFACT_LIST_SCHEMA_VERSION;
  readonly reasonCode: "ARTIFACT_LIST_READY";
  readonly artifacts: readonly (ArtifactManifestEntry & { readonly present: boolean })[];
  readonly unindexed: readonly string[];
}

/**
 * What the manifest records, and what the root holds that the manifest does not.
 *
 * The root's absolute path is deliberately NOT reported. It is a local address that
 * differs on every machine, and a receipt that carries one turns a portable manifest
 * into a machine-bound one the moment anybody stores the receipt.
 */
export async function listArtifacts(workspaceRootInput: string): Promise<ArtifactListing> {
  const workspace = await boundDirectory(workspaceRootInput);
  const root = await assertGeneratedArtifactsRoot(workspace, await effectiveArtifactsSetting(workspace));
  const manifest = await readManifest(workspace);
  const onDisk = new Set((await readdir(root)).filter((name) => name.endsWith(BLOB_SUFFIX)));
  const indexed = new Set(manifest.artifacts.map((entry) => `${entry.sha256}${BLOB_SUFFIX}`));
  return {
    schemaVersion: ARTIFACT_LIST_SCHEMA_VERSION,
    reasonCode: "ARTIFACT_LIST_READY",
    artifacts: manifest.artifacts.map((entry) => ({ ...entry, present: onDisk.has(`${entry.sha256}${BLOB_SUFFIX}`) })),
    unindexed: [...onDisk].filter((name) => !indexed.has(name)).sort(compareCanonicalText),
  };
}

export interface ArtifactVerification {
  readonly schemaVersion: typeof ARTIFACT_VERIFY_SCHEMA_VERSION;
  readonly reasonCode: "ARTIFACT_VERIFIED" | "ARTIFACT_MISMATCH";
  readonly checked: number;
  readonly findings: readonly ArtifactVerifyFinding[];
}

/**
 * Recompute every blob the manifest records and report each one that disagrees.
 *
 * This reports rather than throws: a verification that stops at the first bad blob tells
 * an operator one name when what they need is the extent of the damage. The reason code
 * carries the verdict, which is the same division `verifySnapshotManifest` makes.
 */
export async function verifyArtifacts(workspaceRootInput: string): Promise<ArtifactVerification> {
  const workspace = await boundDirectory(workspaceRootInput);
  const root = await assertGeneratedArtifactsRoot(workspace, await effectiveArtifactsSetting(workspace));
  const manifest = await readManifest(workspace);
  const findings: ArtifactVerifyFinding[] = [];
  for (const entry of manifest.artifacts) {
    const target = blobPath(root, entry.sha256);
    const stats = await lstat(target).catch(() => null);
    if (stats === null || !stats.isFile() || stats.isSymbolicLink()) {
      findings.push({ sha256: entry.sha256, finding: "missing", detail: `${entry.sha256}${BLOB_SUFFIX} is not a regular file in the artifact root` });
      continue;
    }
    if (stats.size !== entry.storedBytes) {
      findings.push({ sha256: entry.sha256, finding: "size-mismatch", detail: `stored ${String(stats.size)} bytes, manifest records ${String(entry.storedBytes)}` });
      continue;
    }
    const stored = await boundFileBytes(target, ARTIFACT_BYTES_MAX);
    const readBack = inflateStoredBlob(stored);
    if ("error" in readBack) {
      findings.push({ sha256: entry.sha256, finding: "unreadable", detail: readBack.error });
      continue;
    }
    const actual = sha256(readBack.plaintext);
    if (actual !== entry.sha256) {
      findings.push({ sha256: entry.sha256, finding: "digest-mismatch", detail: `content hashes to ${actual}` });
      continue;
    }
    if (readBack.plaintext.length !== entry.bytes) {
      findings.push({ sha256: entry.sha256, finding: "size-mismatch", detail: `content is ${String(readBack.plaintext.length)} bytes, manifest records ${String(entry.bytes)}` });
    }
  }
  return {
    schemaVersion: ARTIFACT_VERIFY_SCHEMA_VERSION,
    reasonCode: findings.length === 0 ? "ARTIFACT_VERIFIED" : "ARTIFACT_MISMATCH",
    checked: manifest.artifacts.length,
    findings,
  };
}
