// SPDX-License-Identifier: Apache-2.0

export const FRAMEWORK_VERSION = "0.10.0" as const;
export const DEFAULT_MODE = "development" as const;

export type WorkflowMode = "development" | "release";

export type RootKind =
  | "framework"
  | "workspace"
  | "transient"
  | "evidence-locator"
  | "release-trust";

export interface ExplicitRoot {
  readonly kind: RootKind;
  readonly path: string;
}

export interface DevelopmentAdmission {
  readonly admitted: true;
  readonly mode: "development";
  readonly projectCommandNetwork: "process-guarded-offline";
  readonly osNetworkSandbox: "not-provided";
  readonly telemetry: "disabled";
}

export interface ReleaseAdmissionRequest {
  readonly mode: "release";
  readonly trustRootPath: string;
  readonly bundlePath: string;
  readonly subject: string;
  readonly repository: string;
  readonly workflow: string;
}

export function admitDevelopment(): DevelopmentAdmission {
  return {
    admitted: true,
    mode: DEFAULT_MODE,
    projectCommandNetwork: "process-guarded-offline",
    osNetworkSandbox: "not-provided",
    telemetry: "disabled",
  };
}

export { assertDistinctRoots, RootIdentityError } from "./root-identity.js";
export type { CanonicalRoot } from "./root-identity.js";
export {
  CONTROL_TREE_SKELETON_DIRECTORIES,
  CONTROL_TREE_TRANSPORT_RESIDUE_PATHS,
  SNAPSHOT_REASON_CODES,
  SnapshotError,
  createSnapshotManifest,
  readGovernedDocumentFile,
  readSnapshotManifestFile,
  verifySnapshotManifest,
} from "./workspace-snapshot.js";
export type { SnapshotReasonCode } from "./workspace-snapshot.js";
// WSR-1: governed workspace relocation.
export {
  RELOCATION_ABORT_FORK_RISK,
  RELOCATION_LIMITS,
  RELOCATION_PERMIT_STAGES,
  RELOCATION_REASON_CODES,
  RELOCATION_TARGET_INSPECTION_WINDOW_MS,
  RelocationError,
  WORKSPACE_RELOCATION_AUTHORITY_VERSION,
  WORKSPACE_RELOCATION_INSPECTION_VERSION,
  WORKSPACE_RELOCATION_PLAN_VERSION,
  WORKSPACE_RELOCATION_RECEIPT_VERSION,
  abortWorkspaceRelocation,
  adoptWorkspace,
  canonicalRelocationAuthority,
  inspectWorkspaceRelocation,
  planWorkspaceRelocation,
  readRelocationAuthority,
  relocationVacateCommitment,
  vacateWorkspace,
  validateRelocationAuthorityDocument,
} from "./workspace-relocation.js";
export type {
  AbortOptions,
  AdoptOptions,
  PlanOptions,
  RelocationPermitStage,
  RelocationAuthorityContext,
  RelocationAuthorityDocument,
  RelocationAuthorityFileIdentity,
  RelocationDestination,
  RelocationPermit,
  RelocationReasonCode,
  RelocationReceipt,
  VacateOptions,
} from "./workspace-relocation.js";
export {
  BACKGROUND_RESOURCE_LIMITS,
  BACKGROUND_RESOURCE_REASON_CODES,
  BACKGROUND_RESOURCE_REGISTRATION_VERSION,
  BACKGROUND_RESOURCE_RESIDUE_VERSION,
  BackgroundResourceError,
  buildRegistrationLine,
  buildResidueReport,
  detectResidue,
  parseProcessTable,
  parseRegistrationLine,
  parseRegistry,
} from "./background-resource.js";
export type {
  BackgroundResourceReasonCode,
  ProcessRow,
  ResidueEntry,
  ResidueReason,
  ResidueReport,
  ResidueStatus,
  SpawnRegistration,
} from "./background-resource.js";
export {
  WORKSPACE_CONTROL_DIRECTORY,
  WORKSPACE_REASON_CODES,
  WORKSPACE_RELOCATION_ENTRY_VERSION,
  WORKSPACE_RELOCATION_IDENTITY_VERSION,
  WORKSPACE_RELOCATION_LEDGER_LIMIT,
  WORKSPACE_SCHEMA_VERSION,
  WORKSPACE_STORAGE_VERSION,
  WorkspaceError,
  acquireWorkspaceLease,
  activeBinding,
  activeWorkspaceRoot,
  deriveRelocationId,
  relocationStateAt,
  appendConferencePositionInWorkspace,
  applyWorkspaceMigration,
  assertSupportedWorkspaceFilesystem,
  breakWorkspaceLease,
  breakWorkspaceRecoveryClaim,
  cancelConferenceInWorkspace,
  closeConferenceInWorkspace,
  createGateInWorkspace,
  deleteGateInWorkspace,
  inspectWorkspaceLease,
  assertWorkspaceRecordCount,
  assertWorkspaceRelativePath,
  createProject,
  createWorkspaceArchive,
  createWork,
  annotateWork,
  deleteProject,
  deleteWork,
  enableActorAttestation,
  exportWorkspace,
  initializeWorkspace,
  materializeWorkspace,
  openConferenceInWorkspace,
  planWorkspaceMigration,
  rebuildWorkspaceViews,
  recoverWorkspace,
  transitionGateInWorkspace,
  transitionWork,
  updateProject,
  validateWorkspace,
  withWorkspaceLease,
} from "./workspace.js";
export type {
  ProjectRecord,
  SprintReference,
  WorkspaceAdmission,
  WorkspaceCrashPoint,
  WorkspaceLease,
  WorkspaceMetadata,
  WorkspaceMigrationPlan,
  WorkspaceMutationOptions,
  WorkspaceReasonCode,
  WorkspaceRelocationAuthorityRecord,
  WorkspaceRelocationBasis,
  WorkspaceRelocationEntry,
  WorkspaceRelocationStage,
  WorkspaceRelocationState,
  WorkspaceState,
} from "./workspace.js";
export {
  PUBLIC_AOS_REQUIREMENTS_REASON_CODES,
  PUBLIC_AOS_REQUIREMENTS_READBACK_VERSION,
  PUBLIC_AOS_REQUIREMENTS_VERSION,
  publicAosRequirementsValidReason,
  PublicAosRequirementsError,
  parsePublicAosRequirementsLedger,
  publicAosRequirementsReadback,
  validatePublicAosRequirementsLedger,
} from "./public-aos-requirements.js";
export type {
  PublicAosRequirement,
  PublicAosRequirementMaturity,
  PublicAosRequirementsLedger,
  PublicAosRequirementsReasonCode,
  PublicAosRequirementStatus,
} from "./public-aos-requirements.js";
export {
  ARTIFACT_ARCHIVE_SCHEMA_VERSION,
  ARTIFACT_LIFECYCLE_VERSION,
  ARTIFACT_LIMITS,
  ARTIFACT_REASON_CODES,
  ARTIFACT_RECORD_SCHEMA_VERSION,
  ARTIFACT_STORE_SCHEMA_VERSION,
  ArtifactLifecycleError,
  applyArtifactArchive,
  artifactArchiveDryRun,
  artifactCompactDryRun,
  artifactDoctor,
  artifactSizeReport,
  assertArtifactRelativePath,
  classifyArtifact,
  initializeArtifactStore,
  redactArtifactReference,
  restoreArtifactArchive,
} from "./artifact-lifecycle.js";
export type {
  ArtifactArchiveOptions,
  ArtifactClassification,
  ArtifactDoctorBudgets,
  ArtifactFaultPoint,
  ArtifactKind,
  ArtifactReasonCode,
  ArtifactRecord,
  ArtifactScanOptions,
} from "./artifact-lifecycle.js";
export {
  KNOWLEDGE_CORE_VERSION,
  KNOWLEDGE_LIMITS,
  KNOWLEDGE_METADATA_SCHEMA_VERSION,
  KNOWLEDGE_REASON_CODES,
  KNOWLEDGE_STORE_SCHEMA_VERSION,
  KnowledgeCoreError,
  createKnowledgeUnit,
  evaluateKnowledgeFreshness,
  exportKnowledgeCheckpoint,
  initializeKnowledgeStore,
  knowledgeContextCandidates,
  knowledgeLinkIndexCountsForTest,
  listKnowledgeMetadata,
  readKnowledgeBody,
  readKnowledgeSnippet,
  rebaseKnowledgeStore,
  retireKnowledgeUnit,
  reverifyKnowledgeUnit,
  transitionKnowledgePromotion,
  validateKnowledgeStore,
} from "./knowledge-core.js";
export type {
  CreateKnowledgeUnitInput,
  KnowledgeBodyReadOptions,
  KnowledgeCategory,
  KnowledgeExportDisposition,
  KnowledgeFaultPoint,
  KnowledgeFreshnessState,
  KnowledgeKind,
  KnowledgeLifecycle,
  KnowledgeListQuery,
  KnowledgeMutationOptions,
  KnowledgePromotionState,
  KnowledgeReadOptions,
  KnowledgeReasonCode,
  KnowledgeRetrievalDisposition,
  KnowledgeScope,
  KnowledgeStalenessPolicy,
  KnowledgeUnitMetadata,
} from "./knowledge-core.js";
export {
  OPERATOR_AUTHORITY_BUNDLE_VERSION,
  OPERATOR_AUTHORITY_PINS_VERSION,
  OPERATOR_AUTHORITY_REASON_CODES,
  OperatorAuthorityError,
  assertOperatorMcpAuthorityOutputGranted,
  assertOperatorMcpWriteGranted,
  readOperatorAuthority,
  validateOperatorAuthorityBundle,
  validateOperatorAuthorityPins,
} from "./operator-authority.js";
export type {
  OperatorAuthorityBundle,
  OperatorAuthorityContext,
  OperatorAuthorityFileGrants,
  OperatorAuthorityHostInputs,
  OperatorAuthorityMcpGrant,
  OperatorAuthorityPins,
  OperatorAuthorityReasonCode,
} from "./operator-authority.js";
export {
  CONTEXT_ROUTE_AUTHORITY_VERSION,
  CONTEXT_ROUTE_LIMITS,
  CONTEXT_ROUTE_REASON_CODES,
  CONTEXT_ROUTE_REQUEST_VERSION,
  CONTEXT_ROUTE_RESULT_VERSION,
  ContextRouteError,
  calculateContextRouteRequestDigest,
  readContextRouteAuthorityReceipt,
  routeContext,
  validateContextRouteRequest,
  validateContextRouteAuthorityReceipt,
  validateContextRouteResult,
} from "./context-router.js";
export {
  CODEX_ADAPTER_BUNDLE_VERSION,
  CODEX_ADAPTER_FALLBACK_VERSION,
  CODEX_ADAPTER_HOST_VERSION,
  CODEX_ADAPTER_LIFECYCLE_VERSION,
  CODEX_ADAPTER_INSTALLATION_VERSION,
  CODEX_ADAPTER_REASON_CODES,
  CODEX_ADAPTER_REQUEST_VERSION,
  CODEX_ADAPTER_TEMPLATE_PATHS,
  CodexAdapterError,
  admitCodexAdapterHostInput,
  calculateCodexAdapterRequestDigest,
  codexAdapterAuthorityEmptyFallback,
  generateCodexAdapterBundle,
  planCodexAdapterRollback,
  readCodexAdapterInstallationReceipt,
  simulateCodexAdapterLifecycle,
  validateCodexAdapterBundle,
  validateCodexAdapterRequest,
} from "./codex-adapter.js";
export type {
  CodexAdapterBundle,
  CodexAdapterFile,
  CodexAdapterGovernedAction,
  CodexAdapterHostContext,
  CodexAdapterHostInput,
  CodexAdapterInstallationContext,
  CodexAdapterInstallationEntry,
  CodexAdapterInstallationFileIdentity,
  CodexAdapterInstallationReadOptions,
  CodexAdapterInstallationReceipt,
  CodexAdapterReasonCode,
  CodexAdapterRequest,
} from "./codex-adapter.js";
export {
  CODEX_ACTIVATION_INERT_PREREQUISITE_PATHS,
  CODEX_ACTIVATION_PATHS,
  CODEX_ACTIVATION_REASON_CODES,
  CODEX_ADAPTER_ACTIVATION_HOST_VERSION,
  CODEX_ADAPTER_ACTIVATION_INSTALLATION_VERSION,
  CODEX_ADAPTER_ACTIVATION_VERSION,
  CODEX_ADAPTER_HOST_ACTIVATION_RECEIPT_VERSION,
  CODEX_HOST_ACTIVATION_OBSERVATION_VERSION,
  CODEX_HOOKS_PATH,
  CODEX_SESSION_START_INJECTION_BUDGET_BYTES,
  CODEX_SESSION_START_PATH,
  CODEX_SESSION_START_SCRIPT_VERSION,
  CODEX_SESSION_SUMMARY_PATH,
  CODEX_SESSION_SUMMARY_VERSION,
  CodexActivationError,
  admitCodexAdapterActivationHostInput,
  admitCodexHostActivationObservation,
  assertCodexAdapterActivationHost,
  assertCodexActivationReceiptContext,
  assertCodexHostActivationObservationContext,
  assessCodexActivationTrust,
  codexHookDefinitionForDigests,
  createCodexHostActivationReceipt,
  generateCodexActivationArtifacts,
  generateCodexSessionStartScript,
  generateCodexSessionSummary,
  readCodexActivationInstallationReceipt,
  readCodexHostActivationObservation,
  validateCodexActivationArtifacts,
  validateCodexActivationInstallationReceipt,
  validateCodexSessionSummary,
} from "./codex-adapter-activation.js";
export type {
  CodexAdapterActivationHostContext,
  CodexAdapterActivationHostInput,
  CodexActivationArtifacts,
  CodexActivationBinding,
  CodexActivationInstallationEntry,
  CodexActivationInstallationReceipt,
  CodexActivationReasonCode,
  CodexActivationReceiptContext,
  CodexActivationStage,
  CodexActivationTrustAssessment,
  CodexHostActivationObservation,
  CodexHostActivationObservationContext,
  CodexHostActivationObservationFileIdentity,
  CodexHostActivationObservationFreshness,
  CodexHostActivationReceipt,
  CodexSessionSummary,
} from "./codex-adapter-activation.js";
export {
  APP_SERVER_OBSERVER_VERSION,
  OBSERVED_EVENT_GROUPS,
  OBSERVED_EVENT_METHODS,
  OBSERVED_PROTOCOL_DIGEST,
  OBSERVED_PROTOCOL_HOST,
  OBSERVER_COVERAGE_NOTE,
  OBSERVER_LIMITS,
  OBSERVER_REASON_CODES,
  ObserverError,
  assertPinnedObservation,
  observeAppServerStream,
  validateObservationReceipt,
} from "./app-server-observer.js";
export type {
  ObservationInput,
  ObservationReceipt,
  ObserverReasonCode,
  ProtocolBinding,
} from "./app-server-observer.js";
export {
  COLLECTION_ATTRIBUTION_NOTE,
  COLLECTION_REASON_CODES,
  CollectionError,
  collectConferenceReceipts,
  collectExecutionReceipt,
  verifyCollectedTranscript,
} from "./execution-collection.js";
export type {
  CollectedReceipt,
  CollectionContext,
  CollectionPlanEntry,
  CollectionReasonCode,
  CollectionResult,
  ObservedInvocation,
} from "./execution-collection.js";
export {
  CODEX_EXECUTION_COLLECTION_VERSION,
  CODEX_EXECUTION_REASON_CODES,
  CODEX_EXECUTION_TRANSCRIPT_VERSION,
  CodexExecutionCollectionError,
  collectCodexAppServerExecutions,
  collectCodexExecutionReceipt,
} from "./codex-execution-collection.js";
export type {
  CodexExecutionCollection,
  CodexExecutionObservationInput,
  CodexExecutionReasonCode,
  CodexExecutionRecord,
  CodexExecutionThreadReadback,
  CodexExecutionTranscript,
  CodexObservedExecution,
  CodexUnavailableExecution,
} from "./codex-execution-collection.js";
export {
  OBSERVE_HANDLER_PATH,
  OBSERVE_HANDLER_REASON_CODES,
  OBSERVE_HANDLER_VERSION,
  OBSERVE_LOG_PATH,
  ObserveHandlerError,
  generateObserveHookHandler,
  observeHookHandlerDigest,
  parseObserveLog,
} from "./observe-hook-handler.js";
export type {
  ObserveHandlerOptions,
  ObserveHandlerReasonCode,
  ObserveLogLine,
} from "./observe-hook-handler.js";
export {
  OBSERVE_HOOK_EVENTS,
  RECEIPT_ANCHOR_VERSION,
  RECEIPT_BATCH_VERSION,
  RECEIPT_COVERAGE,
  RECEIPT_COVERAGE_NOTE,
  RECEIPT_ENTRY_VERSION,
  RECEIPT_LIMITS,
  RECEIPT_REASON_CODES,
  ReceiptError,
  anchorReceiptBatch,
  appendReceipt,
  openReceiptBatch,
  pruneReceiptBatches,
  sealReceiptBatch,
  validateReceiptAnchor,
  validateReceiptBatch,
  verifyAnchorAgainstBatch,
} from "./receipt-sidecar.js";
export type {
  AppendReceiptInput,
  ObserveHookEvent,
  ObserveReceipt,
  OpenBatchInput,
  PruneResult,
  ReceiptAnchor,
  ReceiptBatch,
  ReceiptCoverage,
  ReceiptReasonCode,
} from "./receipt-sidecar.js";
export {
  CODEX_ADAPTER_INSTALLER_REASON_CODES,
  CodexAdapterInstallerError,
  admitCodexAdapterInstallationRoot,
  executeCodexAdapterRollback,
  installCodexAdapterActivation,
  installCodexAdapterBundle,
  uninstallCodexAdapterActivation,
} from "./codex-adapter-installer.js";
export type {
  CodexAdapterActivationInstallOptions,
  CodexAdapterActivationInstallResult,
  CodexAdapterActivationUninstallResult,
  CodexAdapterInstallOptions,
  CodexAdapterInstallResult,
  CodexAdapterInstallerReasonCode,
  CodexAdapterRollbackResult,
} from "./codex-adapter-installer.js";
export {
  CLAUDE_ADAPTER_BUNDLE_VERSION,
  CLAUDE_ADAPTER_FALLBACK_VERSION,
  CLAUDE_ADAPTER_FRAGMENT_VERSION,
  CLAUDE_ADAPTER_HOOK_EVENTS,
  CLAUDE_ADAPTER_HOST_PRODUCT,
  CLAUDE_ADAPTER_HOST_VERSION,
  CLAUDE_ADAPTER_LIFECYCLE_VERSION,
  CLAUDE_ADAPTER_INSTALLATION_VERSION,
  CLAUDE_ADAPTER_REASON_CODES,
  CLAUDE_ADAPTER_REQUEST_VERSION,
  CLAUDE_ADAPTER_SETTINGS_TARGET,
  CLAUDE_ADAPTER_FRAGMENT_MERGE_KEY,
  CLAUDE_ADAPTER_TEMPLATE_PATHS,
  ClaudeAdapterError,
  admitClaudeAdapterHostInput,
  assertNoForbiddenClaudePaths,
  calculateClaudeAdapterRequestDigest,
  claudeAdapterAuthorityEmptyFallback,
  generateClaudeAdapterBundle,
  generateClaudeAdapterSettingsFragment,
  mergeClaudeAdapterSettingsFragment,
  planClaudeAdapterRollback,
  readClaudeAdapterInstallationReceipt,
  removeClaudeAdapterSettingsFragment,
  simulateClaudeAdapterLifecycle,
  validateClaudeAdapterBundle,
  validateClaudeAdapterRequest,
  validateClaudeAdapterSettingsFragment,
} from "./claude-adapter.js";
export type {
  ClaudeAdapterBundle,
  ClaudeAdapterFile,
  ClaudeAdapterGovernedAction,
  ClaudeAdapterHostContext,
  ClaudeAdapterHostInput,
  ClaudeAdapterInstallationContext,
  ClaudeAdapterInstallationEntry,
  ClaudeAdapterInstallationFileIdentity,
  ClaudeAdapterInstallationReadOptions,
  ClaudeAdapterInstallationReceipt,
  ClaudeAdapterReasonCode,
  ClaudeAdapterRequest,
} from "./claude-adapter.js";
export {
  CLAUDE_ADAPTER_INSTALLER_REASON_CODES,
  ClaudeAdapterInstallerError,
  admitClaudeAdapterInstallationRoot,
  executeClaudeAdapterRollback,
  installClaudeAdapterActivation,
  installClaudeAdapterBundle,
} from "./claude-adapter-installer.js";
export type {
  ClaudeAdapterActivationInstallOptions,
  ClaudeAdapterActivationInstallResult,
  ClaudeAdapterInstallOptions,
  ClaudeAdapterInstallResult,
  ClaudeAdapterInstallerReasonCode,
  ClaudeAdapterRollbackResult,
} from "./claude-adapter-installer.js";
export {
  CLAUDE_ADAPTER_ACTIVATION_HOOK_EVENT,
  CLAUDE_ADAPTER_ACTIVATION_MERGE_KEY,
  CLAUDE_ADAPTER_ACTIVATION_PATHS,
  CLAUDE_ADAPTER_ACTIVATION_REASON_CODES,
  CLAUDE_ADAPTER_FRAGMENT_V2_VERSION,
  CLAUDE_ADAPTER_HOST_V2_VERSION,
  CLAUDE_ADAPTER_INSTALLATION_V2_VERSION,
  CLAUDE_ADAPTER_ROLLBACK_PLAN_VERSION,
  CLAUDE_ADAPTER_SESSION_START_PATH,
  ClaudeAdapterActivationError,
  admitClaudeAdapterActivationHostInput,
  claudeAdapterActivationHookCommand,
  generateClaudeAdapterActivationFragment,
  generateClaudeAdapterActivationRollbackPlan,
  mergeClaudeAdapterActivationFragment,
  readClaudeAdapterActivationReceipt,
  removeClaudeAdapterActivationFragment,
  validateClaudeAdapterActivationFragment,
  validateClaudeAdapterActivationInstallationReceipt,
} from "./claude-adapter-activation.js";
export type {
  ClaudeAdapterActivationFragment,
  ClaudeAdapterActivationHostContext,
  ClaudeAdapterActivationHostInput,
  ClaudeAdapterActivationInstallationEntry,
  ClaudeAdapterActivationInstallationReceipt,
  ClaudeAdapterActivationReasonCode,
  ClaudeAdapterActivationReceiptContext,
  ClaudeAdapterActivationReceiptFileIdentity,
  ClaudeAdapterActivationScriptContext,
} from "./claude-adapter-activation.js";
export {
  SESSION_START_INJECTION_BUDGET_BYTES,
  SESSION_START_SCRIPT_VERSION,
  generateSessionStartScript,
  sessionStartScriptDigest,
} from "./claude-adapter-session-start.js";
export {
  PERSONA_RENDER_ALLOWED_PROFILE_IDS,
  PERSONA_RENDER_BUDGET_BYTES,
  PERSONA_RENDER_REASON_CODES,
  PERSONA_RENDER_VERSION,
  PersonaRenderError,
  renderPersonaAuthoritySummary,
  validatePersonaAuthorityRender,
} from "./persona-render.js";
export type {
  PersonaAuthorityRender,
  PersonaAuthorityRenderOptions,
  PersonaRenderReasonCode,
} from "./persona-render.js";
export {
  DEPENDENCY_VERSION,
  DEPENDENCY_KINDS,
  DEPENDENCY_STATUSES,
  DEPENDENCY_REASON_CODES,
  DependencyError,
  validateDependencyRecord,
  canonicalDependencyDigest,
  assertDependencyEndpoints,
  orderDependencies,
  assertNoDependencyCycle,
  listDependencyBlockers,
  listDependenciesByWorkItem,
} from "./dependency.js";
export {
  ACTOR_ATTESTATION_SCHEMA_VERSION,
  ACTOR_ATTESTATION_ENABLE_OPERATION,
  ACTOR_ATTESTATION_REGISTRATION_ID,
  ACTOR_PREFIXES,
  ACTOR_ATTESTATION_REASON_CODES,
  ActorAttestationError,
  EVENT_PAYLOAD_OPERATION_EXTRAS,
  assertActorId,
  buildEventPayload,
  buildActorAttestationEnableRecord,
  validateActorAttestationEnableRecord,
  buildActorAttestationRegistration,
} from "./actor-attestation.js";
export type {
  DependencyRecord,
  DependencyWorkReference,
  DependencyReasonCode,
  DependencyKind,
  DependencyStatus,
} from "./dependency.js";
export {
  CONFERENCE_REQUEST_VERSION,
  CONFERENCE_POSITION_VERSION,
  CONFERENCE_MINUTES_VERSION,
  CONFERENCE_TYPES,
  CONFERENCE_STATUSES,
  CONFERENCE_OUTCOME_CLASSES,
  CONFERENCE_REASON_CODES,
  ConferenceError,
  validateConferenceRequest,
  validateConferencePosition,
  validateConferenceMinutes,
  openConference,
  appendConferencePosition,
  listConferencesByWorkItem,
  closeConference,
  distillConferenceKnowledge,
} from "./conference.js";
export type {
  ConferenceRequest,
  ConferencePosition,
  ConferenceMinutes,
  ConferenceDecisionCandidate,
  ConferenceReasonCode,
  DistillConferenceOptions,
} from "./conference.js";
export {
  EXECUTION_MODES,
  HOST_EXECUTION_RECEIPT_VERSION,
  EXECUTION_MODE_EXTENSION_KEY,
  EXECUTION_RECEIPT_EXTENSION_KEY,
  MULTI_AGENT_DEFAULT_TYPES,
  EXECUTION_AVAILABILITY,
  EXECUTION_REASON_CODES,
  ExecutionError,
  validateHostExecutionReceipt,
  readExecutionMode,
  classifyConferenceExecution,
} from "./conference-execution.js";
export type {
  ExecutionMode,
  ExecutionReasonCode,
  HostExecutionReceipt,
  ExecutionModeDeclaration,
  ExecutionClassification,
  ClassifyInput,
} from "./conference-execution.js";
export {
  ASSIGNMENT_VERSION,
  GATE_VERSION,
  ASSIGNMENT_STATUSES,
  GATE_STATUSES,
  GATE_OUTCOME_CLASSES,
  ASSIGNMENT_GATE_REASON_CODES,
  AssignmentGateError,
  validateAssignmentRecord,
  validateGateRecord,
  listAssignmentsByWorkItem,
  listGatesByWorkItem,
} from "./assignment-gate.js";
export type {
  AssignmentRecord,
  GateRecord,
  AssignmentGateReasonCode,
} from "./assignment-gate.js";
export {
  GATE_IDENTITY_AUTHORITY_VERSION,
  GATE_IDENTITY_REASON_CODES,
  GATE_IDENTITY_LIMITS,
  GateIdentityError,
  validateGateIdentityAuthorityDocument,
  readGateIdentityAuthority,
  permitsGateOutcome,
  assertGateOutcomePermitted,
  gateIdentityDecision,
  validateGateIdentityDecision,
  canonicalGateIdentityAuthority,
} from "./gate-identity.js";
export type {
  GateIdentityAuthorityContext,
  GateIdentityAuthorityDocument,
  GateIdentityAuthorityFileIdentity,
  GateIdentityDecision,
  GateIdentityPermit,
  GateIdentityReasonCode,
} from "./gate-identity.js";
export type {
  ContextBudgets,
  ContextExplicitReadCandidate,
  ContextFreshness,
  ContextMetadataCandidate,
  ContextRiskTier,
  ContextRouteAuthorityContext,
  ContextRouteAuthorityFileIdentity,
  ContextRouteAuthorityReceipt,
  ContextRouteOptions,
  ContextRouteReasonCode,
  ContextRouteRequest,
  ContextScope,
  ContextTaskKind,
} from "./context-router.js";
export {
  GENERIC_PROFILE_BUNDLE_VERSION,
  GENERIC_PROFILE_ADMISSION_RECEIPT_VERSION,
  GENERIC_PROFILE_BASE_DIGEST,
  GENERIC_PROFILE_EFFECTIVE_VERSION,
  GENERIC_PROFILE_OPERATIONS,
  GENERIC_PROFILE_OWNER_REBIND_VERSION,
  GENERIC_PROFILE_REASON_CODES,
  GENERIC_PROFILE_VERSION,
  GenericProfileError,
  authorizeGenericProfileOperation,
  calculateGenericProfileAdmissionClaims,
  generateGenericStarterBundle,
  readGenericProfileAdmissionReceipt,
  resolveGenericProfile,
  validateEffectiveGenericProfile,
  validateGenericProfileBinding,
  validateGenericProfileLayer,
  validateGenericStarterBundle,
} from "./generic-profile.js";
export {
  CANONICAL_EXCHANGE_LIMITS,
  CANONICAL_EXCHANGE_MANIFEST_VERSION,
  CANONICAL_EXCHANGE_REASON_CODES,
  CANONICAL_EXCHANGE_REQUEST_VERSION,
  CANONICAL_EXCHANGE_RESUME_VERSION,
  CANONICAL_EXCHANGE_TRANSACTION_VERSION,
  CanonicalExchangeError,
  dryRunCanonicalExchange,
  planCanonicalExchange,
  readCanonicalExchangeBundle,
  validateCanonicalExchangeBundle,
  writeCanonicalExchangeBundle,
} from "./canonical-exchange.js";
export {
  COMPATIBILITY_ADMISSION_VERSION,
  COMPATIBILITY_LIMITS,
  COMPATIBILITY_MANIFEST_VERSION,
  COMPATIBILITY_REASON_CODES,
  COMPATIBILITY_RECEIPT_VERSION,
  COMPATIBILITY_REQUEST_VERSION,
  COMPATIBILITY_RESULT_VERSION,
  CompatibilityError,
  calculateCompatibilityEffectivePlanDigest,
  dryRunCompatibilityMode,
  parseWorkflowCompatibilityManifest,
  planCompatibilityMode,
  readCompatibilityAdmissionReceipt,
  unavailableCompatibilityCapability,
  validateCompatibilityRequest,
  validateWorkflowCompatibilityManifest,
} from "./compatibility-modes.js";
export type {
  CompatibilityAdmissionContext,
  CompatibilityAdmissionAuthority,
  CompatibilityAdmissionReadOptions,
  CompatibilityAdmissionReceipt,
  CompatibilityCheckpoint,
  CompatibilityOperation,
  CompatibilityPairReceipt,
  CompatibilityPlan,
  CompatibilityReasonCode,
  CompatibilityRequest,
  CompatibilityUnavailableSurface,
  CompatibilityWorkspaceLock,
  WorkflowCompatibilityManifest,
} from "./compatibility-modes.js";
export type {
  CanonicalExchangeChunkInput,
  CanonicalExchangeChunkRecord,
  CanonicalExchangeFaultPoint,
  CanonicalExchangeManifest,
  CanonicalExchangePlan,
  CanonicalExchangeReadOptions,
  CanonicalExchangeReadback,
  CanonicalExchangeReasonCode,
  CanonicalExchangeRequest,
  CanonicalExchangeResume,
  CanonicalExchangeTransaction,
  CanonicalExchangeWriteOptions,
} from "./canonical-exchange.js";
export {
  CORE_PERSONA_BUNDLE_VERSION,
  CORE_PERSONA_PROFILE_VERSION,
  CORE_PERSONA_REASON_CODES,
  CORE_PERSONA_SOURCE_MANIFEST_SHA256,
  CORE_REFERENCE_PERSONA_IDS,
  CorePersonaError,
  generateCorePersonaBundle,
  generateCorePersonaReleaseLayers,
  isCoreReferencePersonaId,
  validateCorePersonaBundle,
  validateCorePersonaProfile,
  validateCorePersonaProfileShape,
} from "./core-reference-personas.js";
export type { CorePersonaBundle, CorePersonaProfile, CorePersonaReasonCode } from "./core-reference-personas.js";
export type {
  EffectiveGenericProfile,
  GenericProfileAdmissionContext,
  GenericProfileAdmissionAuthority,
  GenericProfileAdmissionReadOptions,
  GenericProfileAdmissionReceipt,
  GenericProfileAuthorizationContext,
  GenericProfileBinding,
  GenericProfileBindingMode,
  GenericProfileBudgets,
  GenericProfileDisplayFields,
  GenericProfileIdentity,
  GenericProfileImmutableFields,
  GenericProfileLayer,
  GenericProfileLayerAdmission,
  GenericProfileLayerKind,
  GenericProfileOperation,
  GenericProfileOwnerRebind,
  GenericProfileOwnerRebindAdmission,
  GenericProfileOwnerRebindFields,
  GenericProfileReasonCode,
  GenericProfileResolutionRequest,
  GenericProfileRestrictOnlyFields,
  GenericProfileStarterBundle,
  GenericProfileTrustLevel,
} from "./generic-profile.js";
