// SPDX-License-Identifier: Apache-2.0

export const FRAMEWORK_VERSION = "0.14.0" as const;
export const DEFAULT_MODE = "development" as const;

export type WorkflowMode = "development" | "release";

export type RootKind =
  | "framework"
  | "workspace"
  | "transient"
  | "evidence-locator"
  | "release-trust";

export interface ExplicitRoot {
  readonly kind: RootKind;
  readonly path: string;
}

export interface DevelopmentAdmission {
  readonly admitted: true;
  readonly mode: "development";
  readonly projectCommandNetwork: "process-guarded-offline";
  readonly osNetworkSandbox: "not-provided";
  readonly telemetry: "disabled";
}

export interface ReleaseAdmissionRequest {
  readonly mode: "release";
  readonly trustRootPath: string;
  readonly bundlePath: string;
  readonly subject: string;
  readonly repository: string;
  readonly workflow: string;
}

export function admitDevelopment(): DevelopmentAdmission {
  return {
    admitted: true,
    mode: DEFAULT_MODE,
    projectCommandNetwork: "process-guarded-offline",
    osNetworkSandbox: "not-provided",
    telemetry: "disabled",
  };
}

export { assertDistinctRoots, RootIdentityError } from "./root-identity.js";
export type { CanonicalRoot } from "./root-identity.js";
// STORY-174: the storage abstraction is part of the public core surface so the
// PG backend (packages/pg-backend) can implement it. StorageError is the
// fail-closed refusal shape; StorageBackend/FileBackend are the interface and
// the converged file implementation.
export { StorageError, FileBackend, WORKSPACE_CONTROL_DIRECTORY } from "./storage-backend.js";
export type { StorageBackend, WorkspaceCrashPoint } from "./storage-backend.js";
// INC-074: the storage-home sentinel declares where a workspace's chain lives
// after a file→pg migration. The file backend refuses mutating verbs on a
// sentinel workspace (WORKSPACE_STORAGE_RELOCATED), and a PG-facing path must
// name the schema the sentinel declares. Part of the public core surface so the
// CLI/facade can check it.
export {
  STORAGE_HOME_VERSION,
  STORAGE_HOME_FILE_NAME,
  StorageHomeError,
  readStorageHomeDeclaration,
  removeStorageHomeDeclaration,
  sealStorageHomeDeclaration,
  writeStorageHomeDeclaration,
} from "./storage-home.js";
export type { StorageHomeDeclaration } from "./storage-home.js";
// STORY-281: machine-level portal preferences. Deliberately not chain-backed — see
// the module header for why a laptop's default theme is not governed workspace state.
export {
  MACHINE_SETTINGS_CATALOG,
  MACHINE_SETTINGS_DIRECTORY,
  MACHINE_SETTINGS_FILE_NAME,
  MACHINE_SETTINGS_LAYER_KIND,
  MACHINE_SETTINGS_REASON_CODES,
  MACHINE_SETTINGS_VERSION,
  MACHINE_SETTING_KEYS,
  MachineSettingsError,
  applyMachineSettingRemove,
  applyMachineSettingSet,
  assertMachineSettingKey,
  machineSettingsPath,
  readMachineSettings,
  readMachineSettingsCatalog,
  validateMachineSettingValue,
  validateMachineSettingsFile,
} from "./machine-settings.js";
export type { MachineSettingKey, MachineSettingsCatalogEntry, MachineSettingsFile, MachineSettingsReadback } from "./machine-settings.js";
// STORY-177: the knowledge/artifact store data-plane backend is part of the public
// core surface so a future PG store backend can implement it. StoreBackendError is
// the fail-closed refusal shape; FileStoreBackend is the converged file
// implementation; withStoreBackendFactory is the test-seam injection.
export { StoreBackendError, FileStoreBackend, withStoreBackendFactory } from "./store-backend.js";
export type { StoreBackend } from "./store-backend.js";
export {
  CONTROL_TREE_SKELETON_DIRECTORIES,
  CONTROL_TREE_TRANSPORT_RESIDUE_PATHS,
  SNAPSHOT_REASON_CODES,
  SnapshotError,
  createSnapshotManifest,
  readGovernedDocumentFile,
  readSnapshotManifestFile,
  verifySnapshotManifest,
} from "./workspace-snapshot.js";
export type { SnapshotReasonCode } from "./workspace-snapshot.js";
// WSR-1: governed workspace relocation.
export {
  RELOCATION_ABORT_FORK_RISK,
  RELOCATION_LIMITS,
  RELOCATION_PERMIT_STAGES,
  RELOCATION_REASON_CODES,
  RELOCATION_TARGET_INSPECTION_WINDOW_MS,
  RelocationError,
  WORKSPACE_RELOCATION_AUTHORITY_VERSION,
  WORKSPACE_RELOCATION_INSPECTION_VERSION,
  WORKSPACE_RELOCATION_PLAN_VERSION,
  WORKSPACE_RELOCATION_RECEIPT_VERSION,
  abortWorkspaceRelocation,
  adoptWorkspace,
  canonicalRelocationAuthority,
  inspectWorkspaceRelocation,
  planWorkspaceRelocation,
  readRelocationAuthority,
  relocationVacateCommitment,
  vacateWorkspace,
  validateRelocationAuthorityDocument,
} from "./workspace-relocation.js";
export type {
  AbortOptions,
  AdoptOptions,
  PlanOptions,
  RelocationPermitStage,
  RelocationAuthorityContext,
  RelocationAuthorityDocument,
  RelocationAuthorityFileIdentity,
  RelocationDestination,
  RelocationPermit,
  RelocationReasonCode,
  RelocationReceipt,
  VacateOptions,
} from "./workspace-relocation.js";
export {
  BACKGROUND_RESOURCE_LIMITS,
  BACKGROUND_RESOURCE_REASON_CODES,
  BACKGROUND_RESOURCE_REGISTRATION_VERSION,
  BACKGROUND_RESOURCE_RESIDUE_VERSION,
  BackgroundResourceError,
  buildRegistrationLine,
  buildResidueReport,
  detectResidue,
  parseProcessTable,
  parseRegistrationLine,
  parseRegistry,
} from "./background-resource.js";
export type {
  BackgroundResourceReasonCode,
  ProcessRow,
  ResidueEntry,
  ResidueReason,
  ResidueReport,
  ResidueStatus,
  SpawnRegistration,
} from "./background-resource.js";
export {
  WORKSPACE_REASON_CODES,
  WORKSPACE_RELOCATION_ENTRY_VERSION,
  WORKSPACE_RELOCATION_IDENTITY_VERSION,
  WORKSPACE_RELOCATION_LEDGER_LIMIT,
  WORKSPACE_SCHEMA_VERSION,
  WORKSPACE_STORAGE_VERSION,
  WorkspaceError,
  acquireWorkspaceLease,
  activeBinding,
  activeWorkspaceRoot,
  deriveRelocationId,
  relocationStateAt,
  appendConferencePositionInWorkspace,
  admitTemplateInWorkspace,
  applyWorkspaceMigration,
  assertSupportedWorkspaceFilesystem,
  breakWorkspaceLease,
  breakWorkspaceRecoveryClaim,
  cancelConferenceInWorkspace,
  closeConferenceInWorkspace,
  createGateInWorkspace,
  deleteGateInWorkspace,
  inspectWorkspaceLease,
  assertWorkspaceRecordCount,
  assertWorkspaceRelativePath,
  createProject,
  createWorkspaceArchive,
  createWork,
  createWorkDelta,
  annotateWork,
  annotateWorkDelta,
  appendEvents,
  consumeViewWriteFailure,
  deleteProject,
  deleteWork,
  enableActorAttestation,
  exportWorkspace,
  initializeWorkspace,
  materializeWorkspace,
  openConferenceInWorkspace,
  planWorkspaceMigration,
  rebuildWorkspaceViews,
  recoverWorkspace,
  removeHostConfigurationInWorkspace,
  removeCustomPersonaInWorkspace,
  removePersonaBindingInWorkspace,
  removeModelPlanInWorkspace,
  removePersonaInWorkspace,
  restorePersonaPresetInWorkspace,
  overridePersonaPresetInWorkspace,
  assignModelPlanInWorkspace,
  setModelPlanInWorkspace,
  unassignModelPlanInWorkspace,
  setCustomPersonaInWorkspace,
  setHostConfigurationInWorkspace,
  setHostDefaultInWorkspace,
  setPersonaBindingInWorkspace,
  setWorkspaceSetting,
  removeWorkspaceSetting,
  transitionGateInWorkspace,
  transitionWork,
  transitionWorkDelta,
  updateProject,
  validateWorkspace,
  withStorageBackendFactory,
  withWorkspaceLease,
  workspaceBudgets,
} from "./workspace.js";
export type {
  ProjectRecord,
  SprintReference,
  WorkspaceAdmission,
  WorkspaceLease,
  WorkspaceMetadata,
  WorkspaceMigrationPlan,
  WorkspaceMutationOptions,
  WorkspaceReasonCode,
  WorkspaceRelocationAuthorityRecord,
  WorkspaceRelocationBasis,
  WorkspaceRelocationEntry,
  WorkspaceRelocationStage,
  WorkspaceRelocationState,
  WorkspaceState,
} from "./workspace.js";
export {
  BUILTIN_TEMPLATES,
  TEMPLATE_ADMISSION_REASON_CODES,
  TEMPLATE_ADMISSION_RECEIPT_VERSION,
  TEMPLATE_ADMISSION_RECORD_VERSION,
  TEMPLATE_BINDING_VERSION,
  TEMPLATE_COUPLING_ROSTER,
  TEMPLATE_DEFINITION_VERSION,
  TEMPLATE_REGISTRATION_PREFIX,
  TemplateAdmissionError,
  admitTemplate,
  createTemplateAdmissionRecord,
  readTemplateDocumentFile,
  templateBindingFromReceipt,
  templateBindingFromWorkRecord,
  templateDigest,
  templateKey,
  templateRecordForBinding,
  templateRecordMatchesBinding,
  templateRegistration,
  templateRegistrationId,
  templateRegistry,
  validateBoundTemplateWork,
  validateTemplateAdmissionReceipt,
  validateTemplateAdmissionRecord,
  validateTemplateBinding,
  validateTemplateDefinition,
  validateTemplateDocument,
} from "./template-admission.js";
export type {
  TemplateAdmissionReasonCode,
  TemplateAdmissionReceipt,
  TemplateAdmissionRecord,
  TemplateBinding,
  TemplateCoupling,
  TemplateDefinition,
} from "./template-admission.js";
export {
  SETTINGS_CATALOG,
  SETTINGS_CATALOG_VERSION,
  SETTINGS_LAYER_KIND,
  SETTINGS_REASON_CODES,
  WORKSPACE_SETTING_VERSION,
  SettingsError,
  compareEngineVersions,
  createWorkspaceSettingRecord,
  readSettingsCatalog,
  settingsCatalogEntry,
  sortWorkspaceSettings,
  validateSettingValue,
  validateWorkspaceSettingRecord,
} from "./settings.js";
export type {
  SettingKey,
  SettingValueType,
  SettingsCatalogEntry,
  SettingsCatalogReadback,
  SettingsReasonCode,
  WorkspaceSettingRecord,
} from "./settings.js";
export {
  INSTALL_MANIFEST,
  INSTALL_MANIFEST_ITEMS,
  INSTALL_MANIFEST_PROJECTS,
  INSTALL_MANIFEST_REASON_CODES,
  INSTALL_MANIFEST_REQUIRED_ITEM_IDS,
  INSTALL_MANIFEST_VERSION,
  InstallManifestError,
  assertInstallManifestComplete,
  readInstallManifest,
} from "./install-manifest.js";
export type {
  InstallManifestHost,
  InstallManifestItem,
  InstallManifestLayer,
  InstallManifestProject,
  InstallManifestReadback,
  InstallManifestWriter,
  InstallManifestReasonCode,
} from "./install-manifest.js";
export {
  EMPTY_EXECUTION_CONFIG,
  EXECUTION_CONFIG_VERSION,
  EXECUTION_HOSTS,
  EXECUTION_CONFIG_REASON_CODES,
  ExecutionConfigError,
  applyHostConfigDefault,
  applyHostConfigRemove,
  applyHostConfigSet,
  applyLegacyCustomPersonaSet,
  applyCustomPersonaSet,
  applyCustomPersonaRemove,
  applyModelPlanAssignInExecutionConfig,
  applyModelPlanRemoveInExecutionConfig,
  applyModelPlanSetInExecutionConfig,
  applyModelPlanUnassignInExecutionConfig,
  applyPersonaPresetOverrideInExecutionConfig,
  applyPersonaPresetRemoveInExecutionConfig,
  applyPersonaPresetRestoreInExecutionConfig,
  applyPersonaBindingRemove,
  applyPersonaBindingSet,
  assertExecutionHost,
  validateConfigurationName,
  validateExecutionConfigState,
  validateModel,
  validateNote,
} from "./execution-config.js";
export {
  MODEL_PLAN_HOSTS,
  MODEL_PLAN_REASON_CODES,
  MODEL_PLAN_VERSION,
  ModelPlanError,
  assertModelPlanHost,
  applyModelPlanAssign,
  applyModelPlanRemove,
  applyModelPlanSet,
  applyModelPlanUnassign,
  readModelPlans,
  validateModelPlanEffort,
  validateModelPlanModel,
  validateModelPlanName,
  validateModelPlanState,
} from "./model-plan.js";
export type { ModelPlanHost, ModelPlanReasonCode, ModelPlanRecord } from "./model-plan.js";
export {
  AGENT_EFFORT_HOSTS,
  AGENT_EFFORT_NAMES,
  AGENT_EFFORT_ROSTER,
  AGENT_EFFORT_VERSION,
  effortForHost,
} from "./effort.js";
export type { AgentEffortHost, AgentEffortName, AgentEffortRecord } from "./effort.js";
export type {
  ExecutionConfigState,
  ExecutionHost,
  ExecutionConfigReasonCode,
  HostConfigurationRecord,
  HostDefaultRecord,
  PersonaBindingRecord,
} from "./execution-config.js";
export {
  CORE_REFERENCE_PERSONAS,
  EMPTY_PERSONA_STORE,
  PERSONA_REASON_CODES,
  PERSONA_CONTENT_FIELDS,
  PERSONA_NARRATIVE_FIELDS,
  PERSONA_RECORD_VERSION,
  PERSONA_ROLES,
  PERSONA_ROLE_DEFINITIONS,
  PERSONA_STORE_VERSION,
  PersonaStoreError,
  allPersonaReadback,
  applyLegacyPersonaSet,
  applyPersonaPresetOverride,
  applyPersonaPresetRemove,
  applyPersonaPresetRestore,
  applyPersonaRemove,
  applyPersonaSet,
  derivePersonaId,
  personaExists,
  validatePersonaDescription,
  validatePersonaContent,
  validatePersonaJobTitle,
  validatePersonaName,
  validatePersonaPrompt,
  validatePersonaRole,
  validatePersonaStoreState,
  validatePersonaPresetOverride,
} from "./persona-store.js";
export type {
  PersonaReasonCode,
  PersonaRecord,
  PersonaRole,
  PersonaContentField,
  PersonaPresetOverrideRecord,
  PersonaReadback,
  PersonaStoreState,
  ReferencePersonaReadback,
} from "./persona-store.js";
export {
  STORY_SCOPE_HEADINGS,
  storyScopeFromRecord,
  storyScopeNamesOwnerDecider,
  validateStoryRecord,
  validateStoryScope,
  validateTemplateScope,
} from "./story-scope-compliance.js";
export type {
  ScopeTemplateDefinition,
  StoryScopeHeading,
  StoryScopeProblem,
  StoryScopeProblemCode,
  StoryScopeSection,
  StoryScopeValidation,
} from "./story-scope-compliance.js";
// STORY-178: file↔pg bidirectional migration of the workspace data plane
// (event segments, workspace metadata, and the two derived stores).
export {
  WORKSPACE_MIGRATION_REASON_CODES,
  WORKSPACE_MIGRATION_VERIFIED,
  WorkspaceMigrationError,
  executeMigration,
  planMigration,
  rollbackMigration,
  verifyMigration,
} from "./workspace-migration.js";
export type {
  MigrationDirection,
  MigrationOptions,
  MigrationPlan,
  MigrationVerification,
  WorkspaceMigrationReasonCode,
} from "./workspace-migration.js";
export {
  PUBLIC_AOS_REQUIREMENTS_REASON_CODES,
  PUBLIC_AOS_REQUIREMENTS_READBACK_VERSION,
  PUBLIC_AOS_REQUIREMENTS_VERSION,
  publicAosRequirementsValidReason,
  PublicAosRequirementsError,
  parsePublicAosRequirementsLedger,
  publicAosRequirementsReadback,
  validatePublicAosRequirementsLedger,
} from "./public-aos-requirements.js";
export type {
  PublicAosRequirement,
  PublicAosRequirementMaturity,
  PublicAosRequirementsLedger,
  PublicAosRequirementsReasonCode,
  PublicAosRequirementStatus,
} from "./public-aos-requirements.js";
export {
  ARTIFACT_ARCHIVE_SCHEMA_VERSION,
  ARTIFACT_LIFECYCLE_VERSION,
  ARTIFACT_LIMITS,
  ARTIFACT_REASON_CODES,
  ARTIFACT_RECORD_SCHEMA_VERSION,
  ARTIFACT_STORE_SCHEMA_VERSION,
  ArtifactLifecycleError,
  applyArtifactArchive,
  artifactArchiveDryRun,
  artifactCompactDryRun,
  artifactDoctor,
  artifactSizeReport,
  assertArtifactRelativePath,
  classifyArtifact,
  initializeArtifactStore,
  redactArtifactReference,
  restoreArtifactArchive,
} from "./artifact-lifecycle.js";
export type {
  ArtifactArchiveOptions,
  ArtifactClassification,
  ArtifactDoctorBudgets,
  ArtifactFaultPoint,
  ArtifactKind,
  ArtifactReasonCode,
  ArtifactRecord,
  ArtifactScanOptions,
} from "./artifact-lifecycle.js";
export {
  KNOWLEDGE_CORE_VERSION,
  KNOWLEDGE_LIMITS,
  KNOWLEDGE_METADATA_SCHEMA_VERSION,
  KNOWLEDGE_REASON_CODES,
  KNOWLEDGE_STORE_SCHEMA_VERSION,
  KnowledgeCoreError,
  createKnowledgeUnit,
  evaluateKnowledgeFreshness,
  exportKnowledgeCheckpoint,
  initializeKnowledgeStore,
  knowledgeContextCandidates,
  knowledgeLinkIndexCountsForTest,
  listKnowledgeMetadata,
  readKnowledgeBody,
  readKnowledgeSnippet,
  rebaseKnowledgeStore,
  retireKnowledgeUnit,
  reverifyKnowledgeUnit,
  transitionKnowledgePromotion,
  validateKnowledgeStore,
} from "./knowledge-core.js";
export type {
  CreateKnowledgeUnitInput,
  KnowledgeBodyReadOptions,
  KnowledgeCategory,
  KnowledgeExportDisposition,
  KnowledgeFaultPoint,
  KnowledgeFreshnessState,
  KnowledgeKind,
  KnowledgeLifecycle,
  KnowledgeListQuery,
  KnowledgeMutationOptions,
  KnowledgePromotionState,
  KnowledgeReadOptions,
  KnowledgeReasonCode,
  KnowledgeRetrievalDisposition,
  KnowledgeScope,
  KnowledgeStalenessPolicy,
  KnowledgeUnitMetadata,
} from "./knowledge-core.js";
export {
  OPERATOR_AUTHORITY_BUNDLE_VERSION,
  OPERATOR_AUTHORITY_PINS_VERSION,
  OPERATOR_AUTHORITY_REASON_CODES,
  OperatorAuthorityError,
  assertOperatorMcpAuthorityOutputGranted,
  assertOperatorMcpWriteGranted,
  readOperatorAuthority,
  validateOperatorAuthorityBundle,
  validateOperatorAuthorityPins,
} from "./operator-authority.js";
export type {
  OperatorAuthorityBundle,
  OperatorAuthorityContext,
  OperatorAuthorityFileGrants,
  OperatorAuthorityHostInputs,
  OperatorAuthorityMcpGrant,
  OperatorAuthorityPins,
  OperatorAuthorityReasonCode,
} from "./operator-authority.js";
export {
  CONTEXT_ROUTE_AUTHORITY_VERSION,
  CONTEXT_ROUTE_LIMITS,
  CONTEXT_ROUTE_REASON_CODES,
  CONTEXT_ROUTE_REQUEST_VERSION,
  CONTEXT_ROUTE_RESULT_VERSION,
  ContextRouteError,
  calculateContextRouteRequestDigest,
  readContextRouteAuthorityReceipt,
  routeContext,
  validateContextRouteRequest,
  validateContextRouteAuthorityReceipt,
  validateContextRouteResult,
} from "./context-router.js";
export {
  CODEX_ADAPTER_BUNDLE_VERSION,
  CODEX_ADAPTER_FALLBACK_VERSION,
  CODEX_ADAPTER_HOST_VERSION,
  CODEX_ADAPTER_LIFECYCLE_VERSION,
  CODEX_ADAPTER_INSTALLATION_VERSION,
  CODEX_ADAPTER_REASON_CODES,
  CODEX_ADAPTER_REQUEST_VERSION,
  CODEX_ADAPTER_TEMPLATE_PATHS,
  CodexAdapterError,
  admitCodexAdapterHostInput,
  calculateCodexAdapterRequestDigest,
  codexAdapterAuthorityEmptyFallback,
  generateCodexAdapterBundle,
  planCodexAdapterRollback,
  readCodexAdapterInstallationReceipt,
  rebindCodexAdapterInstallation,
  simulateCodexAdapterLifecycle,
  validateCodexAdapterBundle,
  validateCodexAdapterRequest,
} from "./codex-adapter.js";
export type {
  CodexAdapterBundle,
  CodexAdapterFile,
  CodexAdapterGovernedAction,
  CodexAdapterHostContext,
  CodexAdapterHostInput,
  CodexAdapterInstallationContext,
  CodexAdapterInstallationEntry,
  CodexAdapterInstallationFileIdentity,
  CodexAdapterInstallationReadOptions,
  CodexAdapterInstallationReceipt,
  CodexAdapterReasonCode,
  CodexAdapterRequest,
} from "./codex-adapter.js";
export {
  CODEX_ACTIVATION_BASE_PATHS,
  CODEX_ACTIVATION_INERT_PREREQUISITE_PATHS,
  CODEX_ACTIVATION_OBSERVE_PATHS,
  CODEX_ACTIVATION_PATHS,
  CODEX_ADAPTER_OBSERVE_EVENTS,
  CODEX_ACTIVATION_REASON_CODES,
  CODEX_ADAPTER_ACTIVATION_HOST_VERSION,
  CODEX_ADAPTER_ACTIVATION_INSTALLATION_VERSION,
  CODEX_ADAPTER_ACTIVATION_VERSION,
  CODEX_ADAPTER_HOST_ACTIVATION_RECEIPT_VERSION,
  CODEX_HOST_ACTIVATION_OBSERVATION_VERSION,
  CODEX_HOOKS_PATH,
  CODEX_OBSERVE_HANDLER_PATH,
  CODEX_SESSION_START_INJECTION_BUDGET_BYTES,
  CODEX_SESSION_START_PATH,
  CODEX_SESSION_START_SCRIPT_VERSION,
  CODEX_SESSION_SUMMARY_PATH,
  CODEX_SESSION_SUMMARY_VERSION,
  CodexActivationError,
  admitCodexAdapterActivationHostInput,
  admitCodexHostActivationObservation,
  assertCodexAdapterActivationHost,
  assertCodexActivationReceiptContext,
  assertCodexHostActivationObservationContext,
  assessCodexActivationTrust,
  codexHookDefinitionForDigests,
  createCodexHostActivationReceipt,
  generateCodexActivationArtifacts,
  generateCodexSessionStartScript,
  generateCodexSessionSummary,
  mergeCodexAdapterHookFragment,
  readCodexActivationInstallationReceipt,
  readCodexHostActivationObservation,
  removeCodexAdapterHookFragment,
  validateCodexActivationArtifacts,
  validateCodexActivationInstallationReceipt,
  validateCodexSessionSummary,
} from "./codex-adapter-activation.js";
export type {
  CodexAdapterActivationHostContext,
  CodexAdapterActivationHostInput,
  CodexActivationArtifacts,
  CodexActivationBinding,
  CodexActivationInstallationEntry,
  CodexActivationInstallationReceipt,
  CodexActivationReasonCode,
  CodexActivationReceiptContext,
  CodexActivationStage,
  CodexActivationTrustAssessment,
  CodexHostActivationObservation,
  CodexHostActivationObservationContext,
  CodexHostActivationObservationFileIdentity,
  CodexHostActivationObservationFreshness,
  CodexHostActivationReceipt,
  CodexSessionSummary,
} from "./codex-adapter-activation.js";
export {
  ADAPTER_BASELINE_ENTRY_IDS,
  ADAPTER_BASELINE_REASON_CODES,
  ADAPTER_BASELINE_VERSION,
  AdapterBaselineError,
  adapterBaselineJson,
  createAdapterBaseline,
  validateAdapterBaseline,
  validateAdapterSurface,
  validateAdapterUserZone,
} from "./adapter-baseline.js";
export type {
  AdapterBaseline,
  AdapterBaselineDriftCheck,
  AdapterBaselineEntry,
  AdapterBaselineEntryId,
  AdapterBaselineInstallationState,
  AdapterBaselineOwner,
  AdapterBaselineReasonCode,
  AdapterSurfaceValidation,
  AdapterUserZoneValidation,
} from "./adapter-baseline.js";
export {
  APP_SERVER_OBSERVER_VERSION,
  OBSERVED_EVENT_GROUPS,
  OBSERVED_EVENT_METHODS,
  OBSERVED_PROTOCOL_DIGEST,
  OBSERVED_PROTOCOL_HOST,
  OBSERVER_COVERAGE_NOTE,
  OBSERVER_LIMITS,
  OBSERVER_REASON_CODES,
  ObserverError,
  assertPinnedObservation,
  observeAppServerStream,
  validateObservationReceipt,
} from "./app-server-observer.js";
export type {
  ObservationInput,
  ObservationReceipt,
  ObserverReasonCode,
  ProtocolBinding,
} from "./app-server-observer.js";
export {
  COLLECTION_ATTRIBUTION_NOTE,
  COLLECTION_REASON_CODES,
  CollectionError,
  collectConferenceReceipts,
  collectExecutionReceipt,
  verifyCollectedTranscript,
} from "./execution-collection.js";
export type {
  CollectedReceipt,
  CollectionContext,
  CollectionPlanEntry,
  CollectionReasonCode,
  CollectionResult,
  ObservedInvocation,
} from "./execution-collection.js";
export {
  CODEX_EXECUTION_COLLECTION_VERSION,
  CODEX_EXECUTION_REASON_CODES,
  CODEX_EXECUTION_TRANSCRIPT_VERSION,
  CodexExecutionCollectionError,
  collectCodexAppServerExecutions,
  collectCodexExecutionReceipt,
} from "./codex-execution-collection.js";
export type {
  CodexExecutionCollection,
  CodexExecutionObservationInput,
  CodexExecutionReasonCode,
  CodexExecutionRecord,
  CodexExecutionThreadReadback,
  CodexExecutionTranscript,
  CodexObservedExecution,
  CodexUnavailableExecution,
} from "./codex-execution-collection.js";
export {
  OBSERVE_HANDLER_PATH,
  OBSERVE_HANDLER_REASON_CODES,
  OBSERVE_HANDLER_VERSION,
  OBSERVE_LOG_PATH,
  ObserveHandlerError,
  generateObserveHookHandler,
  observeHookHandlerDigest,
  parseObserveLog,
} from "./observe-hook-handler.js";
export type {
  ObserveHandlerOptions,
  ObserveHandlerReasonCode,
  ObserveLogLine,
} from "./observe-hook-handler.js";
export {
  OBSERVE_HOOK_EVENTS,
  RECEIPT_ANCHOR_VERSION,
  RECEIPT_BATCH_VERSION,
  RECEIPT_COVERAGE,
  RECEIPT_COVERAGE_NOTE,
  RECEIPT_ENTRY_VERSION,
  RECEIPT_LIMITS,
  RECEIPT_REASON_CODES,
  ReceiptError,
  anchorReceiptBatch,
  appendReceipt,
  openReceiptBatch,
  pruneReceiptBatches,
  sealReceiptBatch,
  validateReceiptAnchor,
  validateReceiptBatch,
  verifyAnchorAgainstBatch,
} from "./receipt-sidecar.js";
export type {
  AppendReceiptInput,
  ObserveHookEvent,
  ObserveReceipt,
  OpenBatchInput,
  PruneResult,
  ReceiptAnchor,
  ReceiptBatch,
  ReceiptCoverage,
  ReceiptReasonCode,
} from "./receipt-sidecar.js";
export {
  CODEX_ADAPTER_INSTALLER_REASON_CODES,
  CodexAdapterInstallerError,
  admitCodexAdapterInstallationRoot,
  executeCodexAdapterRollback,
  installCodexAdapterActivation,
  installCodexAdapterBundle,
  uninstallCodexAdapterActivation,
} from "./codex-adapter-installer.js";
export type {
  CodexAdapterActivationInstallOptions,
  CodexAdapterActivationInstallResult,
  CodexAdapterActivationUninstallResult,
  CodexAdapterInstallOptions,
  CodexAdapterInstallResult,
  CodexAdapterInstallerReasonCode,
  CodexAdapterRollbackResult,
} from "./codex-adapter-installer.js";
export {
  CLAUDE_ADAPTER_BUNDLE_VERSION,
  CLAUDE_ADAPTER_FALLBACK_VERSION,
  CLAUDE_ADAPTER_FRAGMENT_VERSION,
  CLAUDE_ADAPTER_HOOK_EVENTS,
  CLAUDE_ADAPTER_HOST_PRODUCT,
  CLAUDE_ADAPTER_HOST_VERSION,
  CLAUDE_ADAPTER_LIFECYCLE_VERSION,
  CLAUDE_ADAPTER_INSTALLATION_VERSION,
  CLAUDE_ADAPTER_REASON_CODES,
  CLAUDE_ADAPTER_REQUEST_VERSION,
  CLAUDE_ADAPTER_SETTINGS_TARGET,
  CLAUDE_ADAPTER_FRAGMENT_MERGE_KEY,
  CLAUDE_ADAPTER_TEMPLATE_PATHS,
  ClaudeAdapterError,
  admitClaudeAdapterHostInput,
  assertNoForbiddenClaudePaths,
  calculateClaudeAdapterRequestDigest,
  claudeAdapterAuthorityEmptyFallback,
  generateClaudeAdapterBundle,
  generateClaudeAdapterSettingsFragment,
  mergeClaudeAdapterSettingsFragment,
  planClaudeAdapterRollback,
  readClaudeAdapterInstallationReceipt,
  rebindClaudeAdapterInstallation,
  removeClaudeAdapterSettingsFragment,
  simulateClaudeAdapterLifecycle,
  validateClaudeAdapterBundle,
  validateClaudeAdapterRequest,
  validateClaudeAdapterSettingsFragment,
} from "./claude-adapter.js";
export type {
  ClaudeAdapterBundle,
  ClaudeAdapterFile,
  ClaudeAdapterGovernedAction,
  ClaudeAdapterHostContext,
  ClaudeAdapterHostInput,
  ClaudeAdapterInstallationContext,
  ClaudeAdapterInstallationEntry,
  ClaudeAdapterInstallationFileIdentity,
  ClaudeAdapterInstallationReadOptions,
  ClaudeAdapterInstallationReceipt,
  ClaudeAdapterReasonCode,
  ClaudeAdapterRequest,
} from "./claude-adapter.js";
export {
  CLAUDE_ADAPTER_INSTALLER_REASON_CODES,
  ClaudeAdapterInstallerError,
  admitClaudeAdapterInstallationRoot,
  executeClaudeAdapterRollback,
  installClaudeAdapterActivation,
  installClaudeAdapterBundle,
} from "./claude-adapter-installer.js";
export type {
  ClaudeAdapterActivationInstallOptions,
  ClaudeAdapterActivationInstallResult,
  ClaudeAdapterInstallOptions,
  ClaudeAdapterInstallResult,
  ClaudeAdapterInstallerReasonCode,
  ClaudeAdapterRollbackResult,
} from "./claude-adapter-installer.js";
export {
  CLAUDE_ADAPTER_ACTIVATION_HOOK_EVENT,
  CLAUDE_ADAPTER_ACTIVATION_MERGE_KEY,
  CLAUDE_ADAPTER_ACTIVATION_PATHS,
  CLAUDE_ADAPTER_ACTIVATION_REASON_CODES,
  CLAUDE_ADAPTER_FRAGMENT_V2_VERSION,
  CLAUDE_ADAPTER_HOST_V2_VERSION,
  CLAUDE_ADAPTER_INSTALLATION_V2_VERSION,
  CLAUDE_ADAPTER_ROLLBACK_PLAN_VERSION,
  CLAUDE_ADAPTER_SESSION_START_PATH,
  ClaudeAdapterActivationError,
  admitClaudeAdapterActivationHostInput,
  claudeAdapterActivationHookCommand,
  generateClaudeAdapterActivationFragment,
  generateClaudeAdapterActivationRollbackPlan,
  mergeClaudeAdapterActivationFragment,
  readClaudeAdapterActivationReceipt,
  removeClaudeAdapterActivationFragment,
  validateClaudeAdapterActivationFragment,
  validateClaudeAdapterActivationInstallationReceipt,
} from "./claude-adapter-activation.js";
export type {
  ClaudeAdapterActivationFragment,
  ClaudeAdapterActivationHostContext,
  ClaudeAdapterActivationHostInput,
  ClaudeAdapterActivationInstallationEntry,
  ClaudeAdapterActivationInstallationReceipt,
  ClaudeAdapterActivationReasonCode,
  ClaudeAdapterActivationReceiptContext,
  ClaudeAdapterActivationReceiptFileIdentity,
  ClaudeAdapterActivationScriptContext,
} from "./claude-adapter-activation.js";
export {
  SESSION_START_INJECTION_BUDGET_BYTES,
  SESSION_START_SCRIPT_VERSION,
  generateSessionStartScript,
  sessionStartScriptDigest,
} from "./claude-adapter-session-start.js";
export {
  PERSONA_RENDER_ALLOWED_PROFILE_IDS,
  PERSONA_RENDER_BUDGET_BYTES,
  PERSONA_RENDER_REASON_CODES,
  PERSONA_RENDER_VERSION,
  PersonaRenderError,
  renderPersonaAuthoritySummary,
  validatePersonaAuthorityRender,
} from "./persona-render.js";
export type {
  PersonaAuthorityRender,
  PersonaAuthorityRenderOptions,
  PersonaRenderReasonCode,
} from "./persona-render.js";
export {
  DEPENDENCY_VERSION,
  DEPENDENCY_KINDS,
  DEPENDENCY_STATUSES,
  DEPENDENCY_REASON_CODES,
  DependencyError,
  validateDependencyRecord,
  canonicalDependencyDigest,
  assertDependencyEndpoints,
  orderDependencies,
  assertNoDependencyCycle,
  listDependencyBlockers,
  listDependenciesByWorkItem,
} from "./dependency.js";
export {
  ACTOR_ATTESTATION_SCHEMA_VERSION,
  ACTOR_ATTESTATION_ENABLE_OPERATION,
  ACTOR_ATTESTATION_REGISTRATION_ID,
  ACTOR_PREFIXES,
  ACTOR_ATTESTATION_REASON_CODES,
  ActorAttestationError,
  EVENT_PAYLOAD_OPERATION_EXTRAS,
  assertActorId,
  buildEventPayload,
  buildActorAttestationEnableRecord,
  validateActorAttestationEnableRecord,
  buildActorAttestationRegistration,
} from "./actor-attestation.js";
export type {
  DependencyRecord,
  DependencyWorkReference,
  DependencyReasonCode,
  DependencyKind,
  DependencyStatus,
} from "./dependency.js";
export {
  CONFERENCE_DISTILL_SUMMARY_BYTES,
  CONFERENCE_POSITION_CEILING_BYTES,
  CONFERENCE_REQUEST_VERSION,
  CONFERENCE_POSITION_VERSION,
  CONFERENCE_MINUTES_VERSION,
  CONFERENCE_TYPES,
  CONFERENCE_STATUSES,
  CONFERENCE_OUTCOME_CLASSES,
  CONFERENCE_EXECUTION_FORMS,
  CONFERENCE_REASON_CODES,
  ConferenceError,
  validateConferenceRequest,
  validateConferencePosition,
  validateConferenceMinutes,
  openConference,
  appendConferencePosition,
  listConferencesByWorkItem,
  closeConference,
  distillConferenceKnowledge,
} from "./conference.js";
export type {
  ConferenceRequest,
  ConferencePosition,
  ConferenceMinutes,
  ConferenceDecisionCandidate,
  ConferenceReasonCode,
  DistillConferenceOptions,
} from "./conference.js";
export { VOCABULARY_VERSION, readVocabulary } from "./vocabulary.js";
export {
  EXECUTION_MODES,
  HOST_EXECUTION_RECEIPT_VERSION,
  EXECUTION_MODE_EXTENSION_KEY,
  EXECUTION_RECEIPT_EXTENSION_KEY,
  MULTI_AGENT_DEFAULT_TYPES,
  EXECUTION_AVAILABILITY,
  EXECUTION_REASON_CODES,
  ExecutionError,
  validateHostExecutionReceipt,
  readExecutionMode,
  classifyConferenceExecution,
} from "./conference-execution.js";
export type {
  ExecutionMode,
  ExecutionReasonCode,
  HostExecutionReceipt,
  ExecutionModeDeclaration,
  ExecutionClassification,
  ClassifyInput,
} from "./conference-execution.js";
export {
  ASSIGNMENT_VERSION,
  GATE_VERSION,
  ASSIGNMENT_STATUSES,
  GATE_STATUSES,
  GATE_OUTCOME_CLASSES,
  ASSIGNMENT_GATE_REASON_CODES,
  AssignmentGateError,
  validateAssignmentRecord,
  validateGateRecord,
  listAssignmentsByWorkItem,
  listGatesByWorkItem,
} from "./assignment-gate.js";
export type {
  AssignmentRecord,
  GateRecord,
  AssignmentGateReasonCode,
} from "./assignment-gate.js";
export {
  GATE_IDENTITY_AUTHORITY_VERSION,
  GATE_IDENTITY_REASON_CODES,
  GATE_IDENTITY_LIMITS,
  GateIdentityError,
  validateGateIdentityAuthorityDocument,
  readGateIdentityAuthority,
  permitsGateOutcome,
  assertGateOutcomePermitted,
  gateIdentityDecision,
  validateGateIdentityDecision,
  canonicalGateIdentityAuthority,
} from "./gate-identity.js";
export type {
  GateIdentityAuthorityContext,
  GateIdentityAuthorityDocument,
  GateIdentityAuthorityFileIdentity,
  GateIdentityDecision,
  GateIdentityPermit,
  GateIdentityReasonCode,
} from "./gate-identity.js";
export type {
  ContextBudgets,
  ContextExplicitReadCandidate,
  ContextFreshness,
  ContextMetadataCandidate,
  ContextRiskTier,
  ContextRouteAuthorityContext,
  ContextRouteAuthorityFileIdentity,
  ContextRouteAuthorityReceipt,
  ContextRouteOptions,
  ContextRouteReasonCode,
  ContextRouteRequest,
  ContextScope,
  ContextTaskKind,
} from "./context-router.js";
export {
  GENERIC_PROFILE_BUNDLE_VERSION,
  GENERIC_PROFILE_ADMISSION_RECEIPT_VERSION,
  GENERIC_PROFILE_BASE_DIGEST,
  GENERIC_PROFILE_EFFECTIVE_VERSION,
  GENERIC_PROFILE_OPERATIONS,
  GENERIC_PROFILE_OWNER_REBIND_VERSION,
  GENERIC_PROFILE_REASON_CODES,
  GENERIC_PROFILE_VERSION,
  GenericProfileError,
  authorizeGenericProfileOperation,
  calculateGenericProfileAdmissionClaims,
  generateGenericStarterBundle,
  readGenericProfileAdmissionReceipt,
  resolveGenericProfile,
  validateEffectiveGenericProfile,
  validateGenericProfileBinding,
  validateGenericProfileLayer,
  validateGenericStarterBundle,
} from "./generic-profile.js";
export {
  CANONICAL_EXCHANGE_LIMITS,
  CANONICAL_EXCHANGE_MANIFEST_VERSION,
  CANONICAL_EXCHANGE_REASON_CODES,
  CANONICAL_EXCHANGE_REQUEST_VERSION,
  CANONICAL_EXCHANGE_RESUME_VERSION,
  CANONICAL_EXCHANGE_TRANSACTION_VERSION,
  CanonicalExchangeError,
  dryRunCanonicalExchange,
  planCanonicalExchange,
  readCanonicalExchangeBundle,
  validateCanonicalExchangeBundle,
  writeCanonicalExchangeBundle,
} from "./canonical-exchange.js";
export {
  COMPATIBILITY_ADMISSION_VERSION,
  COMPATIBILITY_LIMITS,
  COMPATIBILITY_MANIFEST_VERSION,
  COMPATIBILITY_REASON_CODES,
  COMPATIBILITY_RECEIPT_VERSION,
  COMPATIBILITY_REQUEST_VERSION,
  COMPATIBILITY_RESULT_VERSION,
  CompatibilityError,
  calculateCompatibilityEffectivePlanDigest,
  dryRunCompatibilityMode,
  parseWorkflowCompatibilityManifest,
  planCompatibilityMode,
  readCompatibilityAdmissionReceipt,
  unavailableCompatibilityCapability,
  validateCompatibilityRequest,
  validateWorkflowCompatibilityManifest,
} from "./compatibility-modes.js";
export type {
  CompatibilityAdmissionContext,
  CompatibilityAdmissionAuthority,
  CompatibilityAdmissionReadOptions,
  CompatibilityAdmissionReceipt,
  CompatibilityCheckpoint,
  CompatibilityOperation,
  CompatibilityPairReceipt,
  CompatibilityPlan,
  CompatibilityReasonCode,
  CompatibilityRequest,
  CompatibilityUnavailableSurface,
  CompatibilityWorkspaceLock,
  WorkflowCompatibilityManifest,
} from "./compatibility-modes.js";
export type {
  CanonicalExchangeChunkInput,
  CanonicalExchangeChunkRecord,
  CanonicalExchangeFaultPoint,
  CanonicalExchangeManifest,
  CanonicalExchangePlan,
  CanonicalExchangeReadOptions,
  CanonicalExchangeReadback,
  CanonicalExchangeReasonCode,
  CanonicalExchangeRequest,
  CanonicalExchangeResume,
  CanonicalExchangeTransaction,
  CanonicalExchangeWriteOptions,
} from "./canonical-exchange.js";
export {
  CORE_PERSONA_BUNDLE_VERSION,
  CORE_PERSONA_PROFILE_VERSION,
  CORE_PERSONA_REASON_CODES,
  CORE_PERSONA_SOURCE_MANIFEST_SHA256,
  CORE_REFERENCE_PERSONA_IDS,
  CorePersonaError,
  generateCorePersonaBundle,
  generateCorePersonaReleaseLayers,
  isCoreReferencePersonaId,
  validateCorePersonaBundle,
  validateCorePersonaProfile,
  validateCorePersonaProfileShape,
} from "./core-reference-personas.js";
export type { CorePersonaBundle, CorePersonaProfile, CorePersonaReasonCode } from "./core-reference-personas.js";
export type {
  EffectiveGenericProfile,
  GenericProfileAdmissionContext,
  GenericProfileAdmissionAuthority,
  GenericProfileAdmissionReadOptions,
  GenericProfileAdmissionReceipt,
  GenericProfileAuthorizationContext,
  GenericProfileBinding,
  GenericProfileBindingMode,
  GenericProfileBudgets,
  GenericProfileDisplayFields,
  GenericProfileIdentity,
  GenericProfileImmutableFields,
  GenericProfileLayer,
  GenericProfileLayerAdmission,
  GenericProfileLayerKind,
  GenericProfileOperation,
  GenericProfileOwnerRebind,
  GenericProfileOwnerRebindAdmission,
  GenericProfileOwnerRebindFields,
  GenericProfileReasonCode,
  GenericProfileResolutionRequest,
  GenericProfileRestrictOnlyFields,
  GenericProfileStarterBundle,
  GenericProfileTrustLevel,
} from "./generic-profile.js";
export { WORK_BATCH_SCHEMA_VERSION, WORK_BATCH_VERBS, applyWorkBatch, workBatchReceipt } from "./work-batch.js";
export type { WorkBatchOptions, WorkBatchProblem } from "./work-batch.js";
