// SPDX-License-Identifier: Apache-2.0
//
// INIT-009 EPIC-024 S069-S071: the observe hook handler generator.
//
// Generates the exact, deterministic .mjs source that a registered observe hook runs.
// One handler serves every enumerated observe event; the event name arrives on argv,
// so a host registers the same reviewed bytes for each hook it enables and the
// digest a trust ceremony approves covers all of them.
//
// Every constraint here traces to MIN-046 (the N-2 amendment):
//
//   * Fail-open, always. The whole body is try/catch{}/finally{process.exit(0)}. A
//     broken recorder loses a receipt; it never breaks the user's session. It writes
//     nothing to stdout, because an observe hook must not inject context.
//   * Closed enumeration. An event this handler was not generated for is ignored --
//     silently, and without writing. Widening the surface is a new ruling, so it must
//     require regenerating (and re-approving) the handler bytes, not a config edit.
//   * Self-verification against drift. The handler carries the digest of the manifest
//     it was generated against, re-derives it at entry, and falls silent on mismatch.
//     Claude Code has no per-hook hash gate, so this is the drift defence available
//     there -- and it is deliberately NOT claimed to be equivalent to Codex's
//     per-hash re-approval: it detects payload drift, not wholesale replacement.
//   * No environment trust. The handler reads no environment variable for anything
//     that decides behaviour; its inputs are argv, its own directory, and stdin.
//   * Bounded. Summaries are truncated to the sidecar's summary budget and the raw
//     payload is retained only as a digest, never as a transcript.
//
// The handler appends to the sidecar's newline-delimited log. Sealing, anchoring and
// pruning are governed operations that run later against the same bytes -- the hook
// itself only appends, because it must finish fast and cannot hold a lease.

import { createHash } from "node:crypto";

import { OBSERVE_HOOK_EVENTS, RECEIPT_LIMITS } from "./receipt-sidecar.js";
import type { ObserveHookEvent } from "./receipt-sidecar.js";

export const OBSERVE_HANDLER_VERSION = "tcrn.observe-hook-handler.v1" as const;
export const OBSERVE_HANDLER_PATH = "observe-hook.mjs" as const;
export const OBSERVE_LOG_PATH = "observe-log.jsonl" as const;

export const OBSERVE_HANDLER_REASON_CODES = Object.freeze([
  "OBSERVE_HANDLER_EVENT_UNKNOWN",
  "OBSERVE_HANDLER_DIGEST_INVALID",
  "OBSERVE_HANDLER_EMPTY_SURFACE",
] as const);
export type ObserveHandlerReasonCode = typeof OBSERVE_HANDLER_REASON_CODES[number];

export class ObserveHandlerError extends Error {
  readonly reasonCode: ObserveHandlerReasonCode;
  constructor(reasonCode: ObserveHandlerReasonCode, message: string) {
    super(message);
    this.name = "ObserveHandlerError";
    this.reasonCode = reasonCode;
  }
}

function fail(reasonCode: ObserveHandlerReasonCode, message: string): never {
  throw new ObserveHandlerError(reasonCode, message);
}

export interface ObserveHandlerOptions {
  // The enumerated events this handler is generated for. Must be a non-empty subset
  // of OBSERVE_HOOK_EVENTS: an event outside the amended surface is refused at
  // generation time, so unenumerated coverage cannot be produced at all.
  readonly events: readonly string[];
  // Digest of the manifest the handler is bound to. The handler re-derives the
  // manifest's digest at entry and falls silent on mismatch.
  readonly manifestDigest: string;
}

const shaPattern = /^[a-f0-9]{64}$/u;

// The deterministic handler body, built as a line array so the bytes are stable and
// reviewable -- the same discipline the SessionStart handler uses, because these
// bytes are what a host trust ceremony approves.
function handlerSource(events: readonly ObserveHookEvent[], manifestDigest: string): string {
  const lines = [
    "// SPDX-License-Identifier: Apache-2.0",
    `// Generated by ${OBSERVE_HANDLER_VERSION} — do not edit.`,
    "// Fail-open governed observe hook: appends one bounded receipt line, writes",
    "// nothing to stdout, and always exits 0. It never blocks and never injects.",
    "import { appendFileSync, readFileSync } from \"node:fs\";",
    "import { createHash } from \"node:crypto\";",
    "import { join } from \"node:path\";",
    "",
    `const EVENTS = ${JSON.stringify([...events].sort())};`,
    `const MANIFEST_DIGEST = "${manifestDigest}";`,
    `const SUMMARY_BYTES = ${RECEIPT_LIMITS.summaryBytes};`,
    `const LOG = "${OBSERVE_LOG_PATH}";`,
    "",
    "// Truncate on a code-point boundary so the result is valid UTF-8 and never",
    "// exceeds the byte budget.",
    "const bound = (value) => {",
    "  let result = \"\";",
    "  for (const codePoint of value) {",
    "    if (Buffer.byteLength(result + codePoint, \"utf8\") > SUMMARY_BYTES) break;",
    "    result += codePoint;",
    "  }",
    "  return result;",
    "};",
    "",
    "try {",
    "  const event = process.argv[2];",
    "  // Closed surface: an event this handler was not generated for is ignored.",
    "  if (!EVENTS.includes(event)) throw new Error(\"event\");",
    "",
    "  // Drift self-check: the manifest must still be the bytes this handler was",
    "  // generated against. On mismatch the handler falls silent rather than",
    "  // recording under an authority that may have changed underneath it.",
    "  const manifestBytes = readFileSync(join(import.meta.dirname, \"project.json\"));",
    "  if (createHash(\"sha256\").update(manifestBytes).digest(\"hex\") !== MANIFEST_DIGEST) throw new Error(\"manifest\");",
    "",
    "  // The host's payload arrives on stdin. It is untrusted data: only its digest",
    "  // and a bounded summary are retained, never the payload itself.",
    "  let payload = \"\";",
    "  try { payload = readFileSync(0, \"utf8\"); } catch { payload = \"\"; }",
    "  const detailDigest = payload.length === 0 ? null : createHash(\"sha256\").update(payload, \"utf8\").digest(\"hex\");",
    "",
    "  const line = JSON.stringify({",
    "    schemaVersion: \"tcrn.observe-hook-line.v1\",",
    "    event,",
    "    occurredAt: new Date().toISOString().replace(/\\.\\d{3}Z$/u, \"Z\"),",
    "    summary: bound(event + \" observed\"),",
    "    detailDigest,",
    "  });",
    "  appendFileSync(join(import.meta.dirname, LOG), line + \"\\n\", { mode: 0o600 });",
    "} catch {",
    "  // Fail-open: on every failure path record nothing and disturb nothing.",
    "} finally {",
    "  process.exit(0);",
    "}",
    "",
  ];
  return lines.join("\n");
}

export function generateObserveHookHandler(options: ObserveHandlerOptions): string {
  const events = options.events;
  if (!Array.isArray(events) || events.length === 0) fail("OBSERVE_HANDLER_EMPTY_SURFACE", "events");
  for (const event of events) {
    if (!(OBSERVE_HOOK_EVENTS as readonly string[]).includes(event)) fail("OBSERVE_HANDLER_EVENT_UNKNOWN", String(event));
  }
  if (new Set(events).size !== events.length) fail("OBSERVE_HANDLER_EVENT_UNKNOWN", "duplicate event");
  if (typeof options.manifestDigest !== "string" || !shaPattern.test(options.manifestDigest)) fail("OBSERVE_HANDLER_DIGEST_INVALID", "manifestDigest");
  return handlerSource(events as readonly ObserveHookEvent[], options.manifestDigest);
}

export function observeHookHandlerDigest(source: string): string {
  return createHash("sha256").update(source, "utf8").digest("hex");
}

export interface ObserveLogLine {
  readonly schemaVersion: "tcrn.observe-hook-line.v1";
  readonly event: ObserveHookEvent;
  readonly occurredAt: string;
  readonly summary: string;
  readonly detailDigest: string | null;
}

// Parse the handler's append-only log into append-ready inputs. Malformed lines are
// DROPPED rather than throwing: the log is written by a fail-open recorder that a
// host may kill mid-write, so a torn final line is an expected state, not corruption
// of everything before it. The count of dropped lines is returned so a caller can
// record that the batch is not a complete account -- which is exactly why coverage
// stays `unknown` until a batch is sealed.
export function parseObserveLog(text: unknown): { readonly lines: readonly ObserveLogLine[]; readonly dropped: number } {
  if (typeof text !== "string") return Object.freeze({ lines: [], dropped: 0 });
  const lines: ObserveLogLine[] = [];
  let dropped = 0;
  for (const raw of text.split("\n")) {
    if (raw.trim().length === 0) continue;
    let parsed: unknown;
    try { parsed = JSON.parse(raw); } catch { dropped += 1; continue; }
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) { dropped += 1; continue; }
    const line = parsed as Record<string, unknown>;
    const keys = Object.keys(line).sort();
    const wanted = ["detailDigest", "event", "occurredAt", "schemaVersion", "summary"];
    if (keys.length !== wanted.length || wanted.some((key, index) => key !== keys[index])) { dropped += 1; continue; }
    if (line.schemaVersion !== "tcrn.observe-hook-line.v1") { dropped += 1; continue; }
    if (!(OBSERVE_HOOK_EVENTS as readonly string[]).includes(line.event as string)) { dropped += 1; continue; }
    if (typeof line.occurredAt !== "string" || typeof line.summary !== "string") { dropped += 1; continue; }
    if (line.detailDigest !== null && (typeof line.detailDigest !== "string" || !shaPattern.test(line.detailDigest))) { dropped += 1; continue; }
    lines.push(Object.freeze({
      schemaVersion: "tcrn.observe-hook-line.v1",
      event: line.event as ObserveHookEvent,
      occurredAt: line.occurredAt,
      summary: line.summary,
      detailDigest: line.detailDigest as string | null,
    }));
  }
  return Object.freeze({ lines: Object.freeze(lines), dropped });
}
